// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: config/folderconfiguration.proto

package config

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	fs "github.com/expgo/net/fs"
	_ "github.com/expgo/net/proto/ext"
	github_com_expgo_net_protocol "github.com/expgo/net/protocol"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FolderDeviceConfiguration struct {
	DeviceID           github_com_expgo_net_protocol.DeviceID `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3,customtype=github.com/expgo/net/protocol.DeviceID" json:"deviceID" xml:"id,attr"`
	IntroducedBy       github_com_expgo_net_protocol.DeviceID `protobuf:"bytes,2,opt,name=introduced_by,json=introducedBy,proto3,customtype=github.com/expgo/net/protocol.DeviceID" json:"introducedBy" xml:"introducedBy,attr"`
	EncryptionPassword string                                 `protobuf:"bytes,3,opt,name=encryption_password,json=encryptionPassword,proto3" json:"encryptionPassword" xml:"encryptionPassword"`
}

func (m *FolderDeviceConfiguration) Reset()         { *m = FolderDeviceConfiguration{} }
func (m *FolderDeviceConfiguration) String() string { return proto.CompactTextString(m) }
func (*FolderDeviceConfiguration) ProtoMessage()    {}
func (*FolderDeviceConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5399ac47b64bdc5, []int{0}
}
func (m *FolderDeviceConfiguration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FolderDeviceConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FolderDeviceConfiguration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FolderDeviceConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FolderDeviceConfiguration.Merge(m, src)
}
func (m *FolderDeviceConfiguration) XXX_Size() int {
	return m.ProtoSize()
}
func (m *FolderDeviceConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_FolderDeviceConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_FolderDeviceConfiguration proto.InternalMessageInfo

type FolderConfiguration struct {
	ID                      string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id" xml:"id,attr" nodefault:"true"`
	Label                   string                      `protobuf:"bytes,2,opt,name=label,proto3" json:"label" xml:"label,attr" restart:"false"`
	FilesystemType          fs.FilesystemType           `protobuf:"varint,3,opt,name=filesystem_type,json=filesystemType,proto3,enum=fs.FilesystemType" json:"filesystemType" xml:"filesystemType"`
	Path                    string                      `protobuf:"bytes,4,opt,name=path,proto3" json:"path" xml:"path,attr" default:"~"`
	Type                    FolderType                  `protobuf:"varint,5,opt,name=type,proto3,enum=config.FolderType" json:"type" xml:"type,attr"`
	Devices                 []FolderDeviceConfiguration `protobuf:"bytes,6,rep,name=devices,proto3" json:"devices" xml:"device"`
	RescanIntervalS         int                         `protobuf:"varint,7,opt,name=rescan_interval_s,json=rescanIntervalS,proto3,casttype=int" json:"rescanIntervalS" xml:"rescanIntervalS,attr" default:"3600"`
	FSWatcherEnabled        bool                        `protobuf:"varint,8,opt,name=fs_watcher_enabled,json=fsWatcherEnabled,proto3" json:"fsWatcherEnabled" xml:"fsWatcherEnabled,attr" default:"true"`
	FSWatcherDelayS         int                         `protobuf:"varint,9,opt,name=fs_watcher_delay_s,json=fsWatcherDelayS,proto3,casttype=int" json:"fsWatcherDelayS" xml:"fsWatcherDelayS,attr" default:"10"`
	IgnorePerms             bool                        `protobuf:"varint,10,opt,name=ignore_perms,json=ignorePerms,proto3" json:"ignorePerms" xml:"ignorePerms,attr"`
	AutoNormalize           bool                        `protobuf:"varint,11,opt,name=auto_normalize,json=autoNormalize,proto3" json:"autoNormalize" xml:"autoNormalize,attr" default:"true"`
	MinDiskFree             Size                        `protobuf:"bytes,12,opt,name=min_disk_free,json=minDiskFree,proto3" json:"minDiskFree" xml:"minDiskFree" default:"1 %"`
	Versioning              VersioningConfiguration     `protobuf:"bytes,13,opt,name=versioning,proto3" json:"versioning" xml:"versioning"`
	Copiers                 int                         `protobuf:"varint,14,opt,name=copiers,proto3,casttype=int" json:"copiers" xml:"copiers"`
	PullerMaxPendingKiB     int                         `protobuf:"varint,15,opt,name=puller_max_pending_kib,json=pullerMaxPendingKib,proto3,casttype=int" json:"pullerMaxPendingKiB" xml:"pullerMaxPendingKiB"`
	Hashers                 int                         `protobuf:"varint,16,opt,name=hashers,proto3,casttype=int" json:"hashers" xml:"hashers"`
	Order                   PullOrder                   `protobuf:"varint,17,opt,name=order,proto3,enum=config.PullOrder" json:"order" xml:"order"`
	IgnoreDelete            bool                        `protobuf:"varint,18,opt,name=ignore_delete,json=ignoreDelete,proto3" json:"ignoreDelete" xml:"ignoreDelete"`
	ScanProgressIntervalS   int                         `protobuf:"varint,19,opt,name=scan_progress_interval_s,json=scanProgressIntervalS,proto3,casttype=int" json:"scanProgressIntervalS" xml:"scanProgressIntervalS"`
	PullerPauseS            int                         `protobuf:"varint,20,opt,name=puller_pause_s,json=pullerPauseS,proto3,casttype=int" json:"pullerPauseS" xml:"pullerPauseS"`
	MaxConflicts            int                         `protobuf:"varint,21,opt,name=max_conflicts,json=maxConflicts,proto3,casttype=int" json:"maxConflicts" xml:"maxConflicts" default:"10"`
	DisableSparseFiles      bool                        `protobuf:"varint,22,opt,name=disable_sparse_files,json=disableSparseFiles,proto3" json:"disableSparseFiles" xml:"disableSparseFiles"`
	DisableTempIndexes      bool                        `protobuf:"varint,23,opt,name=disable_temp_indexes,json=disableTempIndexes,proto3" json:"disableTempIndexes" xml:"disableTempIndexes"`
	Paused                  bool                        `protobuf:"varint,24,opt,name=paused,proto3" json:"paused" xml:"paused"`
	WeakHashThresholdPct    int                         `protobuf:"varint,25,opt,name=weak_hash_threshold_pct,json=weakHashThresholdPct,proto3,casttype=int" json:"weakHashThresholdPct" xml:"weakHashThresholdPct"`
	MarkerName              string                      `protobuf:"bytes,26,opt,name=marker_name,json=markerName,proto3" json:"markerName" xml:"markerName"`
	CopyOwnershipFromParent bool                        `protobuf:"varint,27,opt,name=copy_ownership_from_parent,json=copyOwnershipFromParent,proto3" json:"copyOwnershipFromParent" xml:"copyOwnershipFromParent"`
	RawModTimeWindowS       int                         `protobuf:"varint,28,opt,name=mod_time_window_s,json=modTimeWindowS,proto3,casttype=int" json:"modTimeWindowS" xml:"modTimeWindowS"`
	MaxConcurrentWrites     int                         `protobuf:"varint,29,opt,name=max_concurrent_writes,json=maxConcurrentWrites,proto3,casttype=int" json:"maxConcurrentWrites" xml:"maxConcurrentWrites" default:"2"`
	DisableFsync            bool                        `protobuf:"varint,30,opt,name=disable_fsync,json=disableFsync,proto3" json:"disableFsync" xml:"disableFsync"`
	BlockPullOrder          BlockPullOrder              `protobuf:"varint,31,opt,name=block_pull_order,json=blockPullOrder,proto3,enum=config.BlockPullOrder" json:"blockPullOrder" xml:"blockPullOrder"`
	CopyRangeMethod         fs.CopyRangeMethod          `protobuf:"varint,32,opt,name=copy_range_method,json=copyRangeMethod,proto3,enum=fs.CopyRangeMethod" json:"copyRangeMethod" xml:"copyRangeMethod" default:"standard"`
	CaseSensitiveFS         bool                        `protobuf:"varint,33,opt,name=case_sensitive_fs,json=caseSensitiveFs,proto3" json:"caseSensitiveFS" xml:"caseSensitiveFS"`
	JunctionsAsDirs         bool                        `protobuf:"varint,34,opt,name=follow_junctions,json=followJunctions,proto3" json:"junctionsAsDirs" xml:"junctionsAsDirs"`
	SyncOwnership           bool                        `protobuf:"varint,35,opt,name=sync_ownership,json=syncOwnership,proto3" json:"syncOwnership" xml:"syncOwnership"`
	ScanOwnership           bool                        `protobuf:"varint,36,opt,name=scan_ownership,json=scanOwnership,proto3" json:"scanOwnership" xml:"scanOwnership"`
	// Legacy deprecated
	DeprecatedReadOnly       bool    `protobuf:"varint,9000,opt,name=read_only,json=readOnly,proto3" json:"-" xml:"ro,attr,omitempty"`                       // Deprecated: Do not use.
	DeprecatedMinDiskFreePct float64 `protobuf:"fixed64,9001,opt,name=min_disk_free_pct,json=minDiskFreePct,proto3" json:"-" xml:"minDiskFreePct,omitempty"` // Deprecated: Do not use.
	DeprecatedPullers        int     `protobuf:"varint,9002,opt,name=pullers,proto3,casttype=int" json:"-" xml:"pullers,omitempty"`                          // Deprecated: Do not use.
}

func (m *FolderConfiguration) Reset()         { *m = FolderConfiguration{} }
func (m *FolderConfiguration) String() string { return proto.CompactTextString(m) }
func (*FolderConfiguration) ProtoMessage()    {}
func (*FolderConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5399ac47b64bdc5, []int{1}
}
func (m *FolderConfiguration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FolderConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FolderConfiguration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FolderConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FolderConfiguration.Merge(m, src)
}
func (m *FolderConfiguration) XXX_Size() int {
	return m.ProtoSize()
}
func (m *FolderConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_FolderConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_FolderConfiguration proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FolderDeviceConfiguration)(nil), "config.FolderDeviceConfiguration")
	proto.RegisterType((*FolderConfiguration)(nil), "config.FolderConfiguration")
}

func init() { proto.RegisterFile("config/folderconfiguration.proto", fileDescriptor_c5399ac47b64bdc5) }

var fileDescriptor_c5399ac47b64bdc5 = []byte{
	// 2081 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xcd, 0x6f, 0xe4, 0x48,
	0x15, 0x8f, 0x33, 0x5f, 0x49, 0xe5, 0xbb, 0x32, 0x1f, 0xb5, 0x19, 0xb6, 0xab, 0xc7, 0xdb, 0x33,
	0x84, 0xd5, 0x6e, 0x32, 0x93, 0x95, 0x90, 0x18, 0x31, 0xc0, 0x76, 0xb2, 0x11, 0xc3, 0x90, 0x9d,
	0x96, 0x33, 0x30, 0x62, 0x41, 0x32, 0x8e, 0x5d, 0xdd, 0xf1, 0xc6, 0x5f, 0x54, 0xb9, 0x27, 0xe9,
	0x39, 0x8c, 0x96, 0x0b, 0x02, 0xc1, 0x01, 0x85, 0xc3, 0x1e, 0xb8, 0xac, 0x04, 0x07, 0xe0, 0x1f,
	0x00, 0x71, 0xe2, 0x38, 0x17, 0x94, 0x3e, 0x22, 0x0e, 0x25, 0x6d, 0xe6, 0xd6, 0x47, 0x1f, 0x73,
	0x42, 0x55, 0x65, 0xbb, 0x6d, 0xb7, 0xf7, 0xc0, 0xad, 0xeb, 0xf7, 0x7b, 0xf5, 0xde, 0xcf, 0xcf,
	0xaf, 0x5e, 0x3d, 0x37, 0x68, 0xda, 0x61, 0xd0, 0x75, 0x7b, 0x9b, 0xdd, 0xd0, 0x73, 0x08, 0x55,
	0x8b, 0x3e, 0xb5, 0x62, 0x37, 0x0c, 0x36, 0x22, 0x1a, 0xc6, 0x21, 0xbc, 0xaa, 0xc0, 0xb5, 0x5b,
	0x25, 0xcb, 0x78, 0x10, 0x11, 0x65, 0xb0, 0xb6, 0x92, 0x12, 0xcc, 0x7d, 0x99, 0x41, 0x37, 0x53,
	0x28, 0xea, 0x7b, 0x5e, 0x48, 0x1d, 0x42, 0x53, 0xbc, 0x95, 0xe2, 0x2f, 0x08, 0x65, 0x6e, 0x18,
	0xb8, 0x41, 0xaf, 0x26, 0xe2, 0xda, 0xed, 0xd4, 0xea, 0xc0, 0x0b, 0xed, 0xa3, 0xaa, 0x8b, 0xc5,
	0x2e, 0xdb, 0x14, 0xc1, 0x59, 0xba, 0x46, 0x5d, 0xb6, 0x69, 0x87, 0xd1, 0x80, 0x5a, 0x41, 0x8f,
	0xf8, 0x24, 0x3e, 0x0c, 0x9d, 0x94, 0x99, 0x25, 0x27, 0xb1, 0xfa, 0xa9, 0xff, 0xe3, 0x12, 0x78,
	0x6b, 0x57, 0xea, 0xde, 0x21, 0x2f, 0x5c, 0x9b, 0x6c, 0x17, 0xa3, 0xc2, 0x3f, 0x6a, 0x60, 0xd6,
	0x91, 0xb8, 0xe9, 0x3a, 0x48, 0x6b, 0x6a, 0xeb, 0xf3, 0xed, 0x57, 0xaf, 0x39, 0x9e, 0xfa, 0x2f,
	0xc7, 0xf7, 0x7a, 0x6e, 0x7c, 0xd8, 0x3f, 0xd8, 0xb0, 0x43, 0x7f, 0x93, 0x9c, 0x44, 0xbd, 0x70,
	0x33, 0x20, 0xf1, 0xa6, 0xf4, 0x6a, 0x87, 0xde, 0x86, 0x72, 0xf7, 0x78, 0xe7, 0x9c, 0xe3, 0x99,
	0xec, 0xf7, 0x88, 0xe3, 0x19, 0x27, 0xfd, 0x9d, 0x70, 0xbc, 0x70, 0xe2, 0x7b, 0x0f, 0x75, 0xd7,
	0x79, 0xcf, 0x8a, 0x63, 0xaa, 0x8f, 0xce, 0x5a, 0xd7, 0xd2, 0xdf, 0xc9, 0x59, 0x2b, 0xb7, 0xfb,
	0xf5, 0xb0, 0xa5, 0x9d, 0x0e, 0x5b, 0xb9, 0x0f, 0x23, 0x63, 0x1c, 0xf8, 0xb9, 0x06, 0x16, 0xdc,
	0x20, 0xa6, 0xa1, 0xd3, 0xb7, 0x89, 0x63, 0x1e, 0x0c, 0xd0, 0xb4, 0x54, 0x48, 0xff, 0x3f, 0x85,
	0x23, 0x8e, 0xe7, 0xc7, 0x6e, 0xda, 0x83, 0x84, 0xe3, 0x5b, 0x4a, 0x59, 0x01, 0xcc, 0x35, 0xae,
	0x4c, 0xa0, 0x42, 0xa1, 0x51, 0xf2, 0x00, 0x6d, 0xb0, 0x4a, 0x02, 0x9b, 0x0e, 0x22, 0x91, 0x45,
	0x33, 0xb2, 0x18, 0x3b, 0x0e, 0xa9, 0x83, 0x2e, 0x35, 0xb5, 0xf5, 0xd9, 0xf6, 0xd6, 0x88, 0x63,
	0x38, 0xa6, 0x3b, 0x29, 0x9b, 0x70, 0x8c, 0x64, 0xd8, 0x49, 0x4a, 0x37, 0x6a, 0xec, 0xf5, 0x7f,
	0xdd, 0x01, 0xab, 0xea, 0xd5, 0x95, 0x5f, 0xda, 0x3e, 0x98, 0x4e, 0x5f, 0xd6, 0x6c, 0x7b, 0xfb,
	0x9c, 0xe3, 0x69, 0xf9, 0x88, 0xd3, 0xae, 0x88, 0xd0, 0x28, 0xa5, 0xbc, 0x19, 0x84, 0x0e, 0xe9,
	0x5a, 0x7d, 0x2f, 0x7e, 0xa8, 0xc7, 0xb4, 0x4f, 0x8a, 0xef, 0xe0, 0x74, 0xd8, 0x9a, 0x7e, 0xbc,
	0xf3, 0x85, 0x78, 0xb6, 0x69, 0xd7, 0x81, 0x3f, 0x02, 0x57, 0x3c, 0xeb, 0x80, 0x78, 0x32, 0xc5,
	0xb3, 0xed, 0xef, 0x8e, 0x38, 0x56, 0x40, 0xc2, 0x71, 0x53, 0x3a, 0x95, 0xab, 0xd4, 0x2f, 0x25,
	0x2c, 0xb6, 0x68, 0xfc, 0x50, 0xef, 0x5a, 0x1e, 0x93, 0x6e, 0xc1, 0x98, 0xfe, 0x6c, 0xd8, 0x9a,
	0x32, 0xd4, 0x66, 0xd8, 0x03, 0x4b, 0x5d, 0xd7, 0x23, 0x6c, 0xc0, 0x62, 0xe2, 0x9b, 0xa2, 0x7a,
	0x65, 0x92, 0x16, 0xb7, 0xe0, 0x46, 0x97, 0x6d, 0xec, 0xe6, 0xd4, 0xb3, 0x41, 0x44, 0xda, 0xef,
	0x8e, 0x38, 0x5e, 0xec, 0x96, 0xb0, 0x84, 0xe3, 0xeb, 0x32, 0x7a, 0x19, 0xd6, 0x8d, 0x8a, 0x1d,
	0xdc, 0x03, 0x97, 0x23, 0x2b, 0x3e, 0x44, 0x97, 0xa5, 0xfc, 0x6f, 0x8d, 0x38, 0x96, 0xeb, 0x84,
	0xe3, 0xdb, 0x72, 0xbf, 0x58, 0xa4, 0xe2, 0xf3, 0x94, 0xbc, 0x12, 0xc2, 0x67, 0x73, 0xe6, 0xe2,
	0xac, 0xa5, 0xbd, 0x32, 0xe4, 0x36, 0xd8, 0x01, 0x97, 0xa5, 0xd8, 0x2b, 0xa9, 0x58, 0x75, 0x2e,
	0x37, 0xd4, 0xeb, 0x90, 0x62, 0xd7, 0x45, 0x88, 0x58, 0x49, 0x5c, 0x92, 0x21, 0xc4, 0x22, 0x2f,
	0xa3, 0xd9, 0x7c, 0x65, 0x48, 0x2b, 0xf8, 0x33, 0x70, 0x4d, 0x15, 0x36, 0x43, 0x57, 0x9b, 0x97,
	0xd6, 0xe7, 0xb6, 0xee, 0x94, 0x9d, 0xd6, 0x1c, 0xcf, 0x36, 0x16, 0x85, 0x3e, 0xe2, 0x38, 0xdb,
	0x99, 0x70, 0x3c, 0x2f, 0x43, 0xa9, 0xb5, 0x6e, 0x64, 0x04, 0xfc, 0x83, 0x06, 0x56, 0x28, 0x61,
	0xb6, 0x15, 0x98, 0x6e, 0x10, 0x13, 0xfa, 0xc2, 0xf2, 0x4c, 0x86, 0xae, 0x35, 0xb5, 0xf5, 0x2b,
	0xed, 0xde, 0x88, 0xe3, 0x25, 0x45, 0x3e, 0x4e, 0xb9, 0xfd, 0x84, 0xe3, 0x6f, 0x48, 0x4f, 0x15,
	0xbc, 0x9a, 0xa2, 0x0f, 0xbe, 0x79, 0xff, 0xbe, 0x7e, 0xc1, 0xf1, 0x25, 0x37, 0x88, 0x47, 0x67,
	0xad, 0xeb, 0x75, 0xe6, 0x17, 0x67, 0xad, 0xcb, 0xc2, 0xce, 0xa8, 0x06, 0x81, 0xff, 0xd4, 0x00,
	0xec, 0x32, 0xf3, 0xd8, 0x8a, 0xed, 0x43, 0x42, 0x4d, 0x12, 0x58, 0x07, 0x1e, 0x71, 0xd0, 0x4c,
	0x53, 0x5b, 0x9f, 0x69, 0xff, 0x56, 0x3b, 0xe7, 0x78, 0x79, 0x77, 0xff, 0xb9, 0x62, 0x3f, 0x52,
	0xe4, 0x88, 0xe3, 0xe5, 0x2e, 0x2b, 0x63, 0x09, 0xc7, 0xef, 0xaa, 0x22, 0xa8, 0x10, 0x55, 0xb5,
	0x59, 0x8d, 0xdf, 0xa8, 0x35, 0x14, 0x3a, 0x85, 0xc5, 0xe9, 0xb0, 0x35, 0x11, 0xd6, 0x98, 0x08,
	0x0a, 0xff, 0x5e, 0x16, 0xef, 0x10, 0xcf, 0x1a, 0x98, 0x0c, 0xcd, 0xca, 0x9c, 0xfe, 0x46, 0x88,
	0x5f, 0xca, 0xbd, 0xec, 0x08, 0x72, 0x5f, 0xe4, 0x39, 0x77, 0xa3, 0xa0, 0x84, 0xe3, 0xaf, 0x97,
	0xa5, 0x2b, 0xbc, 0xaa, 0xfc, 0x41, 0x29, 0xcb, 0x75, 0xc6, 0x17, 0x67, 0xad, 0xe9, 0x07, 0xf7,
	0x4f, 0x87, 0xad, 0x6a, 0x54, 0xa3, 0x1a, 0x13, 0xfe, 0x1c, 0xcc, 0xbb, 0xbd, 0x20, 0xa4, 0xc4,
	0x8c, 0x08, 0xf5, 0x19, 0x02, 0x32, 0xdf, 0x8f, 0x46, 0x1c, 0xcf, 0x29, 0xbc, 0x23, 0xe0, 0x84,
	0xe3, 0x9b, 0xaa, 0x5b, 0x8c, 0xb1, 0xbc, 0x7c, 0x97, 0xab, 0xa0, 0x51, 0xdc, 0x0a, 0x7f, 0xa9,
	0x81, 0x45, 0xab, 0x1f, 0x87, 0x66, 0x10, 0x52, 0xdf, 0xf2, 0xdc, 0x97, 0x04, 0xcd, 0xc9, 0x20,
	0x9f, 0x8c, 0x38, 0x5e, 0x10, 0xcc, 0xc7, 0x19, 0x91, 0x67, 0xa0, 0x84, 0x7e, 0xd5, 0x9b, 0x83,
	0x93, 0x56, 0xd9, 0x6b, 0x33, 0xca, 0x7e, 0x61, 0x08, 0x16, 0x7c, 0x37, 0x30, 0x1d, 0x97, 0x1d,
	0x99, 0x5d, 0x4a, 0x08, 0x9a, 0x6f, 0x6a, 0xeb, 0x73, 0x5b, 0xf3, 0xd9, 0xb1, 0xda, 0x77, 0x5f,
	0x92, 0xf6, 0xa3, 0xf4, 0x04, 0xcd, 0xf9, 0x6e, 0xb0, 0xe3, 0xb2, 0xa3, 0x5d, 0x4a, 0x84, 0x22,
	0x2c, 0x15, 0x15, 0xb0, 0xe2, 0xab, 0x68, 0xde, 0xd5, 0x2f, 0xce, 0x5a, 0x97, 0x1e, 0x34, 0xef,
	0x1a, 0xc5, 0x6d, 0xb0, 0x07, 0xc0, 0xf8, 0xf6, 0x46, 0x0b, 0x32, 0x1a, 0xce, 0xa2, 0xfd, 0x38,
	0x67, 0xca, 0x47, 0xf8, 0x5e, 0x2a, 0xa0, 0xb0, 0x35, 0xe1, 0x78, 0x59, 0xc6, 0x1f, 0x43, 0xba,
	0x51, 0xe0, 0xe1, 0x23, 0x70, 0xcd, 0x0e, 0x23, 0x97, 0x50, 0x86, 0x16, 0x65, 0xb5, 0xbd, 0x23,
	0x7a, 0x40, 0x0a, 0xe5, 0xf7, 0x6a, 0xba, 0xce, 0xea, 0xc6, 0xc8, 0x0c, 0xe0, 0xbf, 0x35, 0x70,
	0x53, 0xcc, 0x0e, 0x84, 0x9a, 0xbe, 0x75, 0x62, 0x46, 0x24, 0x70, 0xdc, 0xa0, 0x67, 0x1e, 0xb9,
	0x07, 0x68, 0x49, 0xba, 0xfb, 0x5c, 0x14, 0xef, 0x6a, 0x47, 0x9a, 0xec, 0x59, 0x27, 0x1d, 0x65,
	0xf0, 0xc4, 0x6d, 0x8f, 0x38, 0x5e, 0x8d, 0x26, 0xe1, 0x84, 0xe3, 0xb7, 0x54, 0x13, 0x9d, 0xe4,
	0x0a, 0x65, 0x5b, 0xbb, 0xb5, 0x1e, 0x3e, 0x1d, 0xb6, 0xea, 0xe2, 0x1b, 0x35, 0xb6, 0x07, 0x22,
	0x1d, 0x87, 0x16, 0x3b, 0x14, 0xe9, 0x58, 0x1e, 0xa7, 0x23, 0x85, 0xf2, 0x74, 0xa4, 0xeb, 0x71,
	0x3a, 0x52, 0x00, 0x7e, 0x08, 0xae, 0xc8, 0x29, 0x0a, 0xad, 0xc8, 0x5e, 0xbe, 0x92, 0xbd, 0x31,
	0x11, 0xff, 0xa9, 0x20, 0xda, 0x48, 0x5c, 0x76, 0xd2, 0x26, 0xe1, 0x78, 0x4e, 0x7a, 0x93, 0x2b,
	0xdd, 0x50, 0x28, 0x7c, 0x02, 0x16, 0xd2, 0x03, 0xe5, 0x10, 0x8f, 0xc4, 0x04, 0x41, 0x59, 0xec,
	0xf7, 0xe4, 0x64, 0x21, 0x89, 0x1d, 0x89, 0x27, 0x1c, 0xc3, 0xc2, 0x91, 0x52, 0xa0, 0x6e, 0x94,
	0x6c, 0xe0, 0x09, 0x40, 0xb2, 0x4f, 0x47, 0x34, 0xec, 0x51, 0xc2, 0x58, 0xb1, 0x61, 0xaf, 0xca,
	0xe7, 0x13, 0x97, 0xef, 0x0d, 0x61, 0xd3, 0x49, 0x4d, 0x8a, 0x6d, 0x5b, 0x5d, 0x67, 0xb5, 0x6c,
	0xfe, 0xec, 0xf5, 0x9b, 0xe1, 0x3e, 0x58, 0x4c, 0xeb, 0x22, 0xb2, 0xfa, 0x8c, 0x98, 0x0c, 0x5d,
	0x97, 0xf1, 0xde, 0x17, 0xcf, 0xa1, 0x98, 0x8e, 0x20, 0xf6, 0xf3, 0xe7, 0x28, 0x82, 0xb9, 0xf7,
	0x92, 0x29, 0x24, 0x60, 0x41, 0x54, 0x99, 0x48, 0xaa, 0xe7, 0xda, 0x31, 0x43, 0x37, 0xa4, 0xcf,
	0xef, 0x09, 0x9f, 0xbe, 0x75, 0xb2, 0x9d, 0xe1, 0xe3, 0x53, 0x57, 0x00, 0x6b, 0x3b, 0xa0, 0xea,
	0x74, 0x46, 0x69, 0x37, 0x74, 0xc0, 0x75, 0xc7, 0x65, 0xa2, 0x33, 0x9b, 0x2c, 0xb2, 0x28, 0x23,
	0xa6, 0x1c, 0x00, 0xd0, 0x4d, 0xf9, 0x26, 0xe4, 0xc8, 0x95, 0xf2, 0xfb, 0x92, 0x96, 0xa3, 0x45,
	0x3e, 0x72, 0x4d, 0x52, 0xba, 0x51, 0x63, 0x5f, 0x8c, 0x12, 0x13, 0x3f, 0x32, 0xdd, 0xc0, 0x21,
	0x27, 0x84, 0xa1, 0x5b, 0x13, 0x51, 0x9e, 0x11, 0x3f, 0x7a, 0xac, 0xd8, 0x6a, 0x94, 0x02, 0x35,
	0x8e, 0x52, 0x00, 0xe1, 0x16, 0xb8, 0x2a, 0x5f, 0x80, 0x83, 0x90, 0xf4, 0xbb, 0x36, 0xe2, 0x38,
	0x45, 0xf2, 0x1b, 0x5e, 0x2d, 0x75, 0x23, 0xc5, 0x61, 0x0c, 0x6e, 0x1d, 0x13, 0xeb, 0xc8, 0x14,
	0x55, 0x6d, 0xc6, 0x87, 0x94, 0xb0, 0xc3, 0xd0, 0x73, 0xcc, 0xc8, 0x8e, 0xd1, 0x5b, 0x32, 0xe1,
	0xa2, 0xbd, 0x5f, 0x17, 0x26, 0xdf, 0xb7, 0xd8, 0xe1, 0xb3, 0xcc, 0xa0, 0x63, 0xc7, 0x09, 0xc7,
	0x6b, 0xd2, 0x65, 0x1d, 0x99, 0xbf, 0xd4, 0xda, 0xad, 0x70, 0x1b, 0xcc, 0xf9, 0x16, 0x3d, 0x22,
	0xd4, 0x0c, 0x2c, 0x9f, 0xa0, 0x35, 0x39, 0x5c, 0xe9, 0xa2, 0x9d, 0x29, 0xf8, 0x63, 0xcb, 0x27,
	0x79, 0x3b, 0x1b, 0x43, 0xba, 0x51, 0xe0, 0xe1, 0x00, 0xac, 0x89, 0xcf, 0x14, 0x33, 0x3c, 0x0e,
	0x08, 0x65, 0x87, 0x6e, 0x64, 0x76, 0x69, 0xe8, 0x9b, 0x91, 0x45, 0x49, 0x10, 0xa3, 0xdb, 0x32,
	0x05, 0xdf, 0x1e, 0x71, 0x7c, 0x4b, 0x58, 0x3d, 0xcd, 0x8c, 0x76, 0x69, 0xe8, 0x77, 0xa4, 0x49,
	0xc2, 0xf1, 0xdb, 0x59, 0xc7, 0xab, 0xe3, 0x75, 0xe3, 0xab, 0x76, 0xc2, 0x5f, 0x69, 0x60, 0xc5,
	0x0f, 0x1d, 0x33, 0x76, 0x7d, 0x62, 0x1e, 0xbb, 0x81, 0x13, 0x1e, 0x9b, 0x0c, 0x7d, 0x4d, 0x26,
	0xec, 0xa7, 0xe7, 0x1c, 0xaf, 0x18, 0xd6, 0xf1, 0x5e, 0xe8, 0x3c, 0x73, 0x7d, 0xf2, 0x5c, 0xb2,
	0xe2, 0x0e, 0x5f, 0xf4, 0x4b, 0x48, 0x3e, 0x82, 0x96, 0xe1, 0x2c, 0x73, 0xa7, 0xc3, 0xd6, 0xa4,
	0x17, 0xa3, 0xe2, 0x03, 0x7e, 0xa6, 0x81, 0x1b, 0xe9, 0x31, 0xb1, 0xfb, 0x54, 0x68, 0x33, 0x8f,
	0xa9, 0x1b, 0x13, 0x86, 0xde, 0x96, 0x62, 0x7e, 0x28, 0x5a, 0xaf, 0x2a, 0xf8, 0x94, 0x7f, 0x2e,
	0xe9, 0x84, 0xe3, 0xbb, 0x85, 0x53, 0x53, 0xe2, 0x0a, 0x87, 0x67, 0xab, 0x70, 0x76, 0xb4, 0x2d,
	0xa3, 0xce, 0x93, 0x68, 0x62, 0x59, 0x6d, 0x77, 0xd9, 0x20, 0xb0, 0x51, 0x63, 0xdc, 0xc4, 0x52,
	0x62, 0x57, 0xe0, 0xf9, 0xe1, 0x2f, 0x82, 0xba, 0x51, 0xb2, 0x81, 0x1e, 0x58, 0x96, 0xdf, 0xa8,
	0xa6, 0xe8, 0x05, 0xa6, 0xea, 0xaf, 0x58, 0xf6, 0xd7, 0x9b, 0x59, 0x7f, 0x6d, 0x0b, 0x7e, 0xdc,
	0x64, 0xe5, 0x70, 0x7f, 0x50, 0xc2, 0xf2, 0xcc, 0x96, 0x61, 0xdd, 0xa8, 0xd8, 0xc1, 0xdf, 0x69,
	0x60, 0x45, 0x96, 0x90, 0xfc, 0xd4, 0x35, 0xd5, 0xb7, 0x2e, 0x6a, 0xca, 0x78, 0xab, 0xe2, 0x43,
	0x62, 0x3b, 0x8c, 0x06, 0x86, 0xe0, 0xf6, 0x24, 0xd5, 0x7e, 0x22, 0x46, 0x31, 0xbb, 0x0c, 0x26,
	0x1c, 0xaf, 0xe7, 0x65, 0x54, 0xc0, 0x0b, 0x69, 0x64, 0xb1, 0x15, 0x38, 0x16, 0x75, 0xc4, 0xfd,
	0x3f, 0x93, 0x2d, 0x8c, 0xaa, 0x23, 0xf8, 0x67, 0x21, 0xc7, 0x12, 0x0d, 0x94, 0x04, 0xcc, 0x8d,
	0xdd, 0x17, 0x22, 0xa3, 0xe8, 0x8e, 0x4c, 0xe7, 0x89, 0x98, 0x0b, 0xb7, 0x2d, 0x46, 0xf6, 0x33,
	0x6e, 0x57, 0xce, 0x85, 0x76, 0x19, 0x4a, 0x38, 0xbe, 0xa1, 0xc4, 0x94, 0x71, 0x31, 0x03, 0x4d,
	0xd8, 0x4e, 0x42, 0x62, 0x0c, 0xac, 0x04, 0x31, 0x2a, 0x36, 0x0c, 0xfe, 0x49, 0x03, 0xcb, 0xdd,
	0xd0, 0xf3, 0xc2, 0x63, 0xf3, 0xd3, 0x7e, 0x60, 0x8b, 0x71, 0x84, 0x21, 0x7d, 0xac, 0xf2, 0x07,
	0x19, 0xf8, 0x21, 0xdb, 0x71, 0x29, 0x13, 0x2a, 0x3f, 0x2d, 0x43, 0xb9, 0xca, 0x0a, 0x2e, 0x55,
	0x56, 0x6d, 0x27, 0x21, 0xa1, 0xb2, 0x12, 0xc4, 0x58, 0x52, 0x8a, 0x72, 0x18, 0x3e, 0x05, 0x8b,
	0xa2, 0xa2, 0xc6, 0xdd, 0x01, 0xbd, 0x23, 0x25, 0x8a, 0xef, 0xab, 0x05, 0xc1, 0xe4, 0xe7, 0x3a,
	0xe1, 0x78, 0x55, 0x5d, 0x7e, 0x45, 0x54, 0x37, 0xca, 0x56, 0xd2, 0xa1, 0xb8, 0x5f, 0xc7, 0x0e,
	0x5b, 0x05, 0x87, 0xb6, 0x15, 0xd4, 0x38, 0x2c, 0xa2, 0xc2, 0x61, 0x71, 0x0d, 0x8f, 0xc0, 0x2c,
	0x25, 0x96, 0x63, 0x86, 0x81, 0x37, 0x40, 0x7f, 0xd9, 0x95, 0xce, 0xf6, 0xce, 0x39, 0x86, 0x3b,
	0x24, 0xa2, 0xc4, 0xb6, 0x62, 0xe2, 0x18, 0xc4, 0x72, 0x9e, 0x06, 0xde, 0x60, 0xc4, 0xb1, 0xf6,
	0x7e, 0xfe, 0xff, 0x02, 0x0d, 0xe5, 0x00, 0xfb, 0x5e, 0xe8, 0xbb, 0xe2, 0x36, 0x89, 0x07, 0xf2,
	0xff, 0x85, 0x09, 0x14, 0x69, 0xc6, 0x0c, 0x4d, 0x1d, 0xc0, 0x5f, 0x80, 0x95, 0xd2, 0x54, 0x2b,
	0x3b, 0xfc, 0x5f, 0x45, 0x50, 0xad, 0xfd, 0xd1, 0x39, 0xc7, 0x68, 0x1c, 0x74, 0x6f, 0x3c, 0x9b,
	0x76, 0xec, 0x38, 0x0b, 0xdd, 0xa8, 0x8e, 0xb6, 0x1d, 0x3b, 0x2e, 0x28, 0x40, 0x9a, 0xb1, 0x58,
	0x26, 0xe1, 0x4f, 0xc0, 0x35, 0x75, 0xa3, 0x33, 0xf4, 0xb7, 0x5d, 0xd9, 0x8d, 0xbe, 0x23, 0x5a,
	0xe3, 0x38, 0x90, 0x9a, 0xd4, 0x58, 0xf9, 0xe1, 0xd2, 0x2d, 0x05, 0xd7, 0x69, 0x0b, 0x42, 0x9a,
	0x91, 0xf9, 0x6b, 0x3f, 0x7a, 0xfd, 0x65, 0x63, 0x6a, 0xf8, 0x65, 0x63, 0xea, 0xf5, 0x79, 0x43,
	0x1b, 0x9e, 0x37, 0xb4, 0xdf, 0xbf, 0x69, 0x4c, 0x7d, 0xf1, 0xa6, 0xa1, 0x0d, 0xdf, 0x34, 0xa6,
	0xfe, 0xf3, 0xa6, 0x31, 0xf5, 0xc9, 0xed, 0xda, 0xff, 0x70, 0x54, 0x0b, 0x39, 0xb8, 0x2a, 0xff,
	0xcb, 0xf9, 0xe0, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x3c, 0x74, 0x06, 0xab, 0x13, 0x00,
	0x00,
}

func (m *FolderDeviceConfiguration) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FolderDeviceConfiguration) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FolderDeviceConfiguration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EncryptionPassword) > 0 {
		i -= len(m.EncryptionPassword)
		copy(dAtA[i:], m.EncryptionPassword)
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(len(m.EncryptionPassword)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.IntroducedBy.ProtoSize()
		i -= size
		if _, err := m.IntroducedBy.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.DeviceID.ProtoSize()
		i -= size
		if _, err := m.DeviceID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FolderConfiguration) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FolderConfiguration) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FolderConfiguration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeprecatedPullers != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.DeprecatedPullers))
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xb2
		i--
		dAtA[i] = 0xd0
	}
	if m.DeprecatedMinDiskFreePct != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.DeprecatedMinDiskFreePct))))
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xb2
		i--
		dAtA[i] = 0xc9
	}
	if m.DeprecatedReadOnly {
		i--
		if m.DeprecatedReadOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xb2
		i--
		dAtA[i] = 0xc0
	}
	if m.ScanOwnership {
		i--
		if m.ScanOwnership {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xa0
	}
	if m.SyncOwnership {
		i--
		if m.SyncOwnership {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x98
	}
	if m.JunctionsAsDirs {
		i--
		if m.JunctionsAsDirs {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x90
	}
	if m.CaseSensitiveFS {
		i--
		if m.CaseSensitiveFS {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x88
	}
	if m.CopyRangeMethod != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.CopyRangeMethod))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x80
	}
	if m.BlockPullOrder != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.BlockPullOrder))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf8
	}
	if m.DisableFsync {
		i--
		if m.DisableFsync {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf0
	}
	if m.MaxConcurrentWrites != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.MaxConcurrentWrites))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe8
	}
	if m.RawModTimeWindowS != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.RawModTimeWindowS))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe0
	}
	if m.CopyOwnershipFromParent {
		i--
		if m.CopyOwnershipFromParent {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd8
	}
	if len(m.MarkerName) > 0 {
		i -= len(m.MarkerName)
		copy(dAtA[i:], m.MarkerName)
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(len(m.MarkerName)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd2
	}
	if m.WeakHashThresholdPct != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.WeakHashThresholdPct))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc8
	}
	if m.Paused {
		i--
		if m.Paused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc0
	}
	if m.DisableTempIndexes {
		i--
		if m.DisableTempIndexes {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb8
	}
	if m.DisableSparseFiles {
		i--
		if m.DisableSparseFiles {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if m.MaxConflicts != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.MaxConflicts))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if m.PullerPauseS != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.PullerPauseS))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.ScanProgressIntervalS != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.ScanProgressIntervalS))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.IgnoreDelete {
		i--
		if m.IgnoreDelete {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.Order != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.Order))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.Hashers != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.Hashers))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.PullerMaxPendingKiB != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.PullerMaxPendingKiB))
		i--
		dAtA[i] = 0x78
	}
	if m.Copiers != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.Copiers))
		i--
		dAtA[i] = 0x70
	}
	{
		size, err := m.Versioning.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	{
		size, err := m.MinDiskFree.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if m.AutoNormalize {
		i--
		if m.AutoNormalize {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.IgnorePerms {
		i--
		if m.IgnorePerms {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.FSWatcherDelayS != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.FSWatcherDelayS))
		i--
		dAtA[i] = 0x48
	}
	if m.FSWatcherEnabled {
		i--
		if m.FSWatcherEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.RescanIntervalS != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.RescanIntervalS))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Devices) > 0 {
		for iNdEx := len(m.Devices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Devices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFolderconfiguration(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.Type != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Path) > 0 {
		i -= len(m.Path)
		copy(dAtA[i:], m.Path)
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(len(m.Path)))
		i--
		dAtA[i] = 0x22
	}
	if m.FilesystemType != 0 {
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(m.FilesystemType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Label) > 0 {
		i -= len(m.Label)
		copy(dAtA[i:], m.Label)
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(len(m.Label)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintFolderconfiguration(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFolderconfiguration(dAtA []byte, offset int, v uint64) int {
	offset -= sovFolderconfiguration(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FolderDeviceConfiguration) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DeviceID.ProtoSize()
	n += 1 + l + sovFolderconfiguration(uint64(l))
	l = m.IntroducedBy.ProtoSize()
	n += 1 + l + sovFolderconfiguration(uint64(l))
	l = len(m.EncryptionPassword)
	if l > 0 {
		n += 1 + l + sovFolderconfiguration(uint64(l))
	}
	return n
}

func (m *FolderConfiguration) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovFolderconfiguration(uint64(l))
	}
	l = len(m.Label)
	if l > 0 {
		n += 1 + l + sovFolderconfiguration(uint64(l))
	}
	if m.FilesystemType != 0 {
		n += 1 + sovFolderconfiguration(uint64(m.FilesystemType))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovFolderconfiguration(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovFolderconfiguration(uint64(m.Type))
	}
	if len(m.Devices) > 0 {
		for _, e := range m.Devices {
			l = e.ProtoSize()
			n += 1 + l + sovFolderconfiguration(uint64(l))
		}
	}
	if m.RescanIntervalS != 0 {
		n += 1 + sovFolderconfiguration(uint64(m.RescanIntervalS))
	}
	if m.FSWatcherEnabled {
		n += 2
	}
	if m.FSWatcherDelayS != 0 {
		n += 1 + sovFolderconfiguration(uint64(m.FSWatcherDelayS))
	}
	if m.IgnorePerms {
		n += 2
	}
	if m.AutoNormalize {
		n += 2
	}
	l = m.MinDiskFree.ProtoSize()
	n += 1 + l + sovFolderconfiguration(uint64(l))
	l = m.Versioning.ProtoSize()
	n += 1 + l + sovFolderconfiguration(uint64(l))
	if m.Copiers != 0 {
		n += 1 + sovFolderconfiguration(uint64(m.Copiers))
	}
	if m.PullerMaxPendingKiB != 0 {
		n += 1 + sovFolderconfiguration(uint64(m.PullerMaxPendingKiB))
	}
	if m.Hashers != 0 {
		n += 2 + sovFolderconfiguration(uint64(m.Hashers))
	}
	if m.Order != 0 {
		n += 2 + sovFolderconfiguration(uint64(m.Order))
	}
	if m.IgnoreDelete {
		n += 3
	}
	if m.ScanProgressIntervalS != 0 {
		n += 2 + sovFolderconfiguration(uint64(m.ScanProgressIntervalS))
	}
	if m.PullerPauseS != 0 {
		n += 2 + sovFolderconfiguration(uint64(m.PullerPauseS))
	}
	if m.MaxConflicts != 0 {
		n += 2 + sovFolderconfiguration(uint64(m.MaxConflicts))
	}
	if m.DisableSparseFiles {
		n += 3
	}
	if m.DisableTempIndexes {
		n += 3
	}
	if m.Paused {
		n += 3
	}
	if m.WeakHashThresholdPct != 0 {
		n += 2 + sovFolderconfiguration(uint64(m.WeakHashThresholdPct))
	}
	l = len(m.MarkerName)
	if l > 0 {
		n += 2 + l + sovFolderconfiguration(uint64(l))
	}
	if m.CopyOwnershipFromParent {
		n += 3
	}
	if m.RawModTimeWindowS != 0 {
		n += 2 + sovFolderconfiguration(uint64(m.RawModTimeWindowS))
	}
	if m.MaxConcurrentWrites != 0 {
		n += 2 + sovFolderconfiguration(uint64(m.MaxConcurrentWrites))
	}
	if m.DisableFsync {
		n += 3
	}
	if m.BlockPullOrder != 0 {
		n += 2 + sovFolderconfiguration(uint64(m.BlockPullOrder))
	}
	if m.CopyRangeMethod != 0 {
		n += 2 + sovFolderconfiguration(uint64(m.CopyRangeMethod))
	}
	if m.CaseSensitiveFS {
		n += 3
	}
	if m.JunctionsAsDirs {
		n += 3
	}
	if m.SyncOwnership {
		n += 3
	}
	if m.ScanOwnership {
		n += 3
	}
	if m.DeprecatedReadOnly {
		n += 4
	}
	if m.DeprecatedMinDiskFreePct != 0 {
		n += 11
	}
	if m.DeprecatedPullers != 0 {
		n += 3 + sovFolderconfiguration(uint64(m.DeprecatedPullers))
	}
	return n
}

func sovFolderconfiguration(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFolderconfiguration(x uint64) (n int) {
	return sovFolderconfiguration(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FolderDeviceConfiguration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFolderconfiguration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FolderDeviceConfiguration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FolderDeviceConfiguration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DeviceID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntroducedBy", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IntroducedBy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptionPassword", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptionPassword = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFolderconfiguration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FolderConfiguration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFolderconfiguration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FolderConfiguration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FolderConfiguration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Label = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilesystemType", wireType)
			}
			m.FilesystemType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FilesystemType |= fs.FilesystemType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= FolderType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Devices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Devices = append(m.Devices, FolderDeviceConfiguration{})
			if err := m.Devices[len(m.Devices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RescanIntervalS", wireType)
			}
			m.RescanIntervalS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RescanIntervalS |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FSWatcherEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FSWatcherEnabled = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FSWatcherDelayS", wireType)
			}
			m.FSWatcherDelayS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FSWatcherDelayS |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IgnorePerms", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IgnorePerms = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoNormalize", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AutoNormalize = bool(v != 0)
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDiskFree", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinDiskFree.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Versioning", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Versioning.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Copiers", wireType)
			}
			m.Copiers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Copiers |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PullerMaxPendingKiB", wireType)
			}
			m.PullerMaxPendingKiB = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PullerMaxPendingKiB |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hashers", wireType)
			}
			m.Hashers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Hashers |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
			}
			m.Order = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Order |= PullOrder(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IgnoreDelete", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IgnoreDelete = bool(v != 0)
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScanProgressIntervalS", wireType)
			}
			m.ScanProgressIntervalS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ScanProgressIntervalS |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PullerPauseS", wireType)
			}
			m.PullerPauseS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PullerPauseS |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxConflicts", wireType)
			}
			m.MaxConflicts = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxConflicts |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisableSparseFiles", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DisableSparseFiles = bool(v != 0)
		case 23:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisableTempIndexes", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DisableTempIndexes = bool(v != 0)
		case 24:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paused = bool(v != 0)
		case 25:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WeakHashThresholdPct", wireType)
			}
			m.WeakHashThresholdPct = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WeakHashThresholdPct |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 26:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarkerName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarkerName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 27:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CopyOwnershipFromParent", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CopyOwnershipFromParent = bool(v != 0)
		case 28:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawModTimeWindowS", wireType)
			}
			m.RawModTimeWindowS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RawModTimeWindowS |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 29:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxConcurrentWrites", wireType)
			}
			m.MaxConcurrentWrites = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxConcurrentWrites |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 30:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisableFsync", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DisableFsync = bool(v != 0)
		case 31:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockPullOrder", wireType)
			}
			m.BlockPullOrder = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockPullOrder |= BlockPullOrder(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 32:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CopyRangeMethod", wireType)
			}
			m.CopyRangeMethod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CopyRangeMethod |= fs.CopyRangeMethod(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 33:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CaseSensitiveFS", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CaseSensitiveFS = bool(v != 0)
		case 34:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JunctionsAsDirs", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.JunctionsAsDirs = bool(v != 0)
		case 35:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SyncOwnership", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SyncOwnership = bool(v != 0)
		case 36:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScanOwnership", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ScanOwnership = bool(v != 0)
		case 9000:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedReadOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DeprecatedReadOnly = bool(v != 0)
		case 9001:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedMinDiskFreePct", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.DeprecatedMinDiskFreePct = float64(math.Float64frombits(v))
		case 9002:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedPullers", wireType)
			}
			m.DeprecatedPullers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeprecatedPullers |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFolderconfiguration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFolderconfiguration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFolderconfiguration(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFolderconfiguration
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFolderconfiguration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFolderconfiguration
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFolderconfiguration
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFolderconfiguration
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFolderconfiguration        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFolderconfiguration          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFolderconfiguration = fmt.Errorf("proto: unexpected end of group")
)
