// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: config/optionsconfiguration.proto

package config

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/expgo/net/proto/ext"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OptionsConfiguration struct {
	RawListenAddresses          []string `protobuf:"bytes,1,rep,name=listen_addresses,json=listenAddresses,proto3" json:"listenAddresses" xml:"listenAddress" default:"default"`
	RawGlobalAnnServers         []string `protobuf:"bytes,2,rep,name=global_discovery_servers,json=globalDiscoveryServers,proto3" json:"globalAnnounceServers" xml:"globalAnnounceServer" default:"default"`
	GlobalAnnEnabled            bool     `protobuf:"varint,3,opt,name=global_discovery_enabled,json=globalDiscoveryEnabled,proto3" json:"globalAnnounceEnabled" xml:"globalAnnounceEnabled" default:"true"`
	LocalAnnEnabled             bool     `protobuf:"varint,4,opt,name=local_discovery_enabled,json=localDiscoveryEnabled,proto3" json:"localAnnounceEnabled" xml:"localAnnounceEnabled" default:"true"`
	LocalAnnPort                int      `protobuf:"varint,5,opt,name=local_announce_port,json=localAnnouncePort,proto3,casttype=int" json:"localAnnouncePort" xml:"localAnnouncePort" default:"21027"`
	LocalAnnMCAddr              string   `protobuf:"bytes,6,opt,name=local_announce_multicast_address,json=localAnnounceMulticastAddress,proto3" json:"localAnnounceMCAddr" xml:"localAnnounceMCAddr" default:"[ff12::8384]:21027"`
	MaxSendKbps                 int      `protobuf:"varint,7,opt,name=max_send_kbps,json=maxSendKbps,proto3,casttype=int" json:"maxSendKbps" xml:"maxSendKbps"`
	MaxRecvKbps                 int      `protobuf:"varint,8,opt,name=max_recv_kbps,json=maxRecvKbps,proto3,casttype=int" json:"maxRecvKbps" xml:"maxRecvKbps"`
	ReconnectIntervalS          int      `protobuf:"varint,9,opt,name=reconnection_interval_s,json=reconnectionIntervalS,proto3,casttype=int" json:"reconnectionIntervalS" xml:"reconnectionIntervalS" default:"60"`
	RelaysEnabled               bool     `protobuf:"varint,10,opt,name=relays_enabled,json=relaysEnabled,proto3" json:"relaysEnabled" xml:"relaysEnabled" default:"true"`
	RelayReconnectIntervalM     int      `protobuf:"varint,11,opt,name=relays_reconnect_interval_m,json=relaysReconnectIntervalM,proto3,casttype=int" json:"relayReconnectIntervalM" xml:"relayReconnectIntervalM" default:"10"`
	StartBrowser                bool     `protobuf:"varint,12,opt,name=start_browser,json=startBrowser,proto3" json:"startBrowser" xml:"startBrowser" default:"true"`
	NATEnabled                  bool     `protobuf:"varint,14,opt,name=nat_traversal_enabled,json=natTraversalEnabled,proto3" json:"natEnabled" xml:"natEnabled" default:"true"`
	NATLeaseM                   int      `protobuf:"varint,15,opt,name=nat_traversal_lease_m,json=natTraversalLeaseM,proto3,casttype=int" json:"natLeaseMinutes" xml:"natLeaseMinutes" default:"60"`
	NATRenewalM                 int      `protobuf:"varint,16,opt,name=nat_traversal_renewal_m,json=natTraversalRenewalM,proto3,casttype=int" json:"natRenewalMinutes" xml:"natRenewalMinutes" default:"30"`
	NATTimeoutS                 int      `protobuf:"varint,17,opt,name=nat_traversal_timeout_s,json=natTraversalTimeoutS,proto3,casttype=int" json:"natTimeoutSeconds" xml:"natTimeoutSeconds" default:"10"`
	URAccepted                  int      `protobuf:"varint,18,opt,name=usage_reporting_accepted,json=usageReportingAccepted,proto3,casttype=int" json:"urAccepted" xml:"urAccepted"`
	URSeen                      int      `protobuf:"varint,19,opt,name=usage_reporting_seen,json=usageReportingSeen,proto3,casttype=int" json:"urSeen" xml:"urSeen"`
	URUniqueID                  string   `protobuf:"bytes,20,opt,name=usage_reporting_unique_id,json=usageReportingUniqueId,proto3" json:"urUniqueId" xml:"urUniqueID"`
	URURL                       string   `protobuf:"bytes,21,opt,name=usage_reporting_url,json=usageReportingUrl,proto3" json:"urURL" xml:"urURL" default:"https://data.syncthing.net/newdata"`
	URPostInsecurely            bool     `protobuf:"varint,22,opt,name=usage_reporting_post_insecurely,json=usageReportingPostInsecurely,proto3" json:"urPostInsecurely" xml:"urPostInsecurely" default:"false"`
	URInitialDelayS             int      `protobuf:"varint,23,opt,name=usage_reporting_initial_delay_s,json=usageReportingInitialDelayS,proto3,casttype=int" json:"urInitialDelayS" xml:"urInitialDelayS" default:"1800"`
	AutoUpgradeIntervalH        int      `protobuf:"varint,25,opt,name=auto_upgrade_interval_h,json=autoUpgradeIntervalH,proto3,casttype=int" json:"autoUpgradeIntervalH" xml:"autoUpgradeIntervalH" default:"12"`
	UpgradeToPreReleases        bool     `protobuf:"varint,26,opt,name=upgrade_to_pre_releases,json=upgradeToPreReleases,proto3" json:"upgradeToPreReleases" xml:"upgradeToPreReleases"`
	KeepTemporariesH            int      `protobuf:"varint,27,opt,name=keep_temporaries_h,json=keepTemporariesH,proto3,casttype=int" json:"keepTemporariesH" xml:"keepTemporariesH" default:"24"`
	CacheIgnoredFiles           bool     `protobuf:"varint,28,opt,name=cache_ignored_files,json=cacheIgnoredFiles,proto3" json:"cacheIgnoredFiles" xml:"cacheIgnoredFiles" default:"false"`
	ProgressUpdateIntervalS     int      `protobuf:"varint,29,opt,name=progress_update_interval_s,json=progressUpdateIntervalS,proto3,casttype=int" json:"progressUpdateIntervalS" xml:"progressUpdateIntervalS" default:"5"`
	LimitBandwidthInLan         bool     `protobuf:"varint,30,opt,name=limit_bandwidth_in_lan,json=limitBandwidthInLan,proto3" json:"limitBandwidthInLan" xml:"limitBandwidthInLan" default:"false"`
	MinHomeDiskFree             Size     `protobuf:"bytes,31,opt,name=min_home_disk_free,json=minHomeDiskFree,proto3" json:"minHomeDiskFree" xml:"minHomeDiskFree" default:"1 %"`
	ReleasesURL                 string   `protobuf:"bytes,32,opt,name=releases_url,json=releasesUrl,proto3" json:"releasesURL" xml:"releasesURL" default:"https://upgrades.syncthing.net/meta.json"`
	AlwaysLocalNets             []string `protobuf:"bytes,33,rep,name=always_local_nets,json=alwaysLocalNets,proto3" json:"alwaysLocalNets" xml:"alwaysLocalNet"`
	OverwriteRemoteDevNames     bool     `protobuf:"varint,34,opt,name=overwrite_remote_device_names_on_connect,json=overwriteRemoteDeviceNamesOnConnect,proto3" json:"overwriteRemoteDeviceNamesOnConnect" xml:"overwriteRemoteDeviceNamesOnConnect" default:"false"`
	TempIndexMinBlocks          int      `protobuf:"varint,35,opt,name=temp_index_min_blocks,json=tempIndexMinBlocks,proto3,casttype=int" json:"tempIndexMinBlocks" xml:"tempIndexMinBlocks" default:"10"`
	UnackedNotificationIDs      []string `protobuf:"bytes,36,rep,name=unacked_notification_ids,json=unackedNotificationIds,proto3" json:"unackedNotificationIDs" xml:"unackedNotificationID"`
	TrafficClass                int      `protobuf:"varint,37,opt,name=traffic_class,json=trafficClass,proto3,casttype=int" json:"trafficClass" xml:"trafficClass"`
	DeprecatedDefaultFolderPath string   `protobuf:"bytes,38,opt,name=default_folder_path,json=defaultFolderPath,proto3" json:"-" xml:"defaultFolderPath,omitempty"` // Deprecated: Do not use.
	SetLowPriority              bool     `protobuf:"varint,39,opt,name=set_low_priority,json=setLowPriority,proto3" json:"setLowPriority" xml:"setLowPriority" default:"true"`
	RawMaxFolderConcurrency     int      `protobuf:"varint,40,opt,name=max_folder_concurrency,json=maxFolderConcurrency,proto3,casttype=int" json:"maxFolderConcurrency" xml:"maxFolderConcurrency"`
	CRURL                       string   `protobuf:"bytes,41,opt,name=crash_reporting_url,json=crashReportingUrl,proto3" json:"crURL" xml:"crashReportingURL" default:"https://crash.syncthing.net/newcrash"`
	CREnabled                   bool     `protobuf:"varint,42,opt,name=crash_reporting_enabled,json=crashReportingEnabled,proto3" json:"crashReportingEnabled" xml:"crashReportingEnabled" default:"true"`
	StunKeepaliveStartS         int      `protobuf:"varint,43,opt,name=stun_keepalive_start_s,json=stunKeepaliveStartS,proto3,casttype=int" json:"stunKeepaliveStartS" xml:"stunKeepaliveStartS" default:"180"`
	StunKeepaliveMinS           int      `protobuf:"varint,44,opt,name=stun_keepalive_min_s,json=stunKeepaliveMinS,proto3,casttype=int" json:"stunKeepaliveMinS" xml:"stunKeepaliveMinS" default:"20"`
	RawStunServers              []string `protobuf:"bytes,45,rep,name=stun_servers,json=stunServers,proto3" json:"stunServers" xml:"stunServer" default:"default"`
	DatabaseTuning              Tuning   `protobuf:"varint,46,opt,name=database_tuning,json=databaseTuning,proto3,enum=config.Tuning" json:"databaseTuning" xml:"databaseTuning" restart:"true"`
	RawMaxCIRequestKiB          int      `protobuf:"varint,47,opt,name=max_concurrent_incoming_request_kib,json=maxConcurrentIncomingRequestKib,proto3,casttype=int" json:"maxConcurrentIncomingRequestKiB" xml:"maxConcurrentIncomingRequestKiB"`
	AnnounceLANAddresses        bool     `protobuf:"varint,48,opt,name=announce_lan_addresses,json=announceLanAddresses,proto3" json:"announceLANAddresses" xml:"announceLANAddresses" default:"true"`
	SendFullIndexOnUpgrade      bool     `protobuf:"varint,49,opt,name=send_full_index_on_upgrade,json=sendFullIndexOnUpgrade,proto3" json:"sendFullIndexOnUpgrade" xml:"sendFullIndexOnUpgrade"`
	FeatureFlags                []string `protobuf:"bytes,50,rep,name=feature_flags,json=featureFlags,proto3" json:"featureFlags" xml:"featureFlag"`
	// The number of connections at which we stop trying to connect to more
	// devices, zero meaning no limit. Does not affect incoming connections.
	ConnectionLimitEnough int `protobuf:"varint,51,opt,name=connection_limit_enough,json=connectionLimitEnough,proto3,casttype=int" json:"connectionLimitEnough" xml:"connectionLimitEnough"`
	// The maximum number of connections which we will allow in total, zero
	// meaning no limit. Affects incoming connections and prevents
	// attempting outgoing connections.
	ConnectionLimitMax int `protobuf:"varint,52,opt,name=connection_limit_max,json=connectionLimitMax,proto3,casttype=int" json:"connectionLimitMax" xml:"connectionLimitMax"`
	// When set, this allows TLS 1.2 on sync connections, where we otherwise
	// default to TLS 1.3+ only.
	InsecureAllowOldTLSVersions bool `protobuf:"varint,53,opt,name=insecure_allow_old_tls_versions,json=insecureAllowOldTlsVersions,proto3" json:"insecureAllowOldTLSVersions" xml:"insecureAllowOldTLSVersions"`
	// Legacy deprecated
	DeprecatedUPnPEnabled        bool     `protobuf:"varint,9000,opt,name=upnp_enabled,json=upnpEnabled,proto3" json:"-" xml:"upnpEnabled,omitempty"`                                    // Deprecated: Do not use.
	DeprecatedUPnPLeaseM         int      `protobuf:"varint,9001,opt,name=upnp_lease_m,json=upnpLeaseM,proto3,casttype=int" json:"-" xml:"upnpLeaseMinutes,omitempty"`                   // Deprecated: Do not use.
	DeprecatedUPnPRenewalM       int      `protobuf:"varint,9002,opt,name=upnp_renewal_m,json=upnpRenewalM,proto3,casttype=int" json:"-" xml:"upnpRenewalMinutes,omitempty"`             // Deprecated: Do not use.
	DeprecatedUPnPTimeoutS       int      `protobuf:"varint,9003,opt,name=upnp_timeout_s,json=upnpTimeoutS,proto3,casttype=int" json:"-" xml:"upnpTimeoutSeconds,omitempty"`             // Deprecated: Do not use.
	DeprecatedRelayServers       []string `protobuf:"bytes,9004,rep,name=relay_servers,json=relayServers,proto3" json:"-" xml:"relayServer,omitempty"`                                   // Deprecated: Do not use.
	DeprecatedMinHomeDiskFreePct float64  `protobuf:"fixed64,9005,opt,name=min_home_disk_free_pct,json=minHomeDiskFreePct,proto3" json:"-" xml:"minHomeDiskFreePct,omitempty"`           // Deprecated: Do not use.
	DeprecatedMaxConcurrentScans int      `protobuf:"varint,9006,opt,name=max_concurrent_scans,json=maxConcurrentScans,proto3,casttype=int" json:"-" xml:"maxConcurrentScans,omitempty"` // Deprecated: Do not use.
}

func (m *OptionsConfiguration) Reset()         { *m = OptionsConfiguration{} }
func (m *OptionsConfiguration) String() string { return proto.CompactTextString(m) }
func (*OptionsConfiguration) ProtoMessage()    {}
func (*OptionsConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_e90aa67e456d8350, []int{0}
}
func (m *OptionsConfiguration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OptionsConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OptionsConfiguration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OptionsConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionsConfiguration.Merge(m, src)
}
func (m *OptionsConfiguration) XXX_Size() int {
	return m.ProtoSize()
}
func (m *OptionsConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionsConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_OptionsConfiguration proto.InternalMessageInfo

func init() {
	proto.RegisterType((*OptionsConfiguration)(nil), "config.OptionsConfiguration")
}

func init() { proto.RegisterFile("config/optionsconfiguration.proto", fileDescriptor_e90aa67e456d8350) }

var fileDescriptor_e90aa67e456d8350 = []byte{
	// 3256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x5a, 0x5d, 0x6c, 0x1d, 0x47,
	0x15, 0xce, 0x26, 0x4d, 0xda, 0x6c, 0x1c, 0x27, 0x1e, 0x3b, 0xf6, 0x36, 0x4e, 0xbd, 0xee, 0xcd,
	0x4d, 0xeb, 0xfe, 0x25, 0xb6, 0x93, 0x86, 0x34, 0x52, 0x55, 0xfc, 0x53, 0x53, 0x37, 0x76, 0x62,
	0x8d, 0x6d, 0x40, 0x45, 0x68, 0x35, 0xde, 0x3b, 0xd7, 0x5e, 0xbc, 0x77, 0xf6, 0x76, 0x67, 0xd6,
	0x3f, 0x2d, 0x82, 0xaa, 0x08, 0xca, 0x1b, 0x60, 0xf1, 0x23, 0x81, 0x84, 0x8a, 0x00, 0x89, 0x52,
	0x8a, 0x90, 0x90, 0x90, 0xe0, 0x85, 0x0a, 0x09, 0xa9, 0x82, 0x07, 0xdf, 0x47, 0x24, 0xca, 0xa2,
	0x3a, 0x7d, 0xba, 0x0f, 0x48, 0xdc, 0x47, 0xf3, 0x82, 0x66, 0xf6, 0x6f, 0x76, 0x77, 0x6e, 0x92,
	0xb7, 0xbb, 0xe7, 0x3b, 0xe7, 0xcc, 0x77, 0xe6, 0xe7, 0xcc, 0x99, 0x99, 0xab, 0x3f, 0x6e, 0x7b,
	0xa4, 0xee, 0xac, 0x5f, 0xf1, 0x9a, 0xcc, 0xf1, 0x08, 0x8d, 0xbe, 0x02, 0x1f, 0xf1, 0xaf, 0xcb,
	0x4d, 0xdf, 0x63, 0x1e, 0x38, 0x11, 0x09, 0xcf, 0xf7, 0xc7, 0xaa, 0x2c, 0x20, 0x0e, 0x59, 0x8f,
	0xc0, 0xf3, 0x7d, 0xb1, 0x90, 0x3a, 0x6f, 0xe0, 0x58, 0x74, 0x12, 0xef, 0xb0, 0xe8, 0x67, 0xe5,
	0xbf, 0xf3, 0xfa, 0xc0, 0x9d, 0xc8, 0xf3, 0x8c, 0xec, 0x19, 0xfc, 0x54, 0xd3, 0xcf, 0xba, 0x0e,
	0x65, 0x98, 0x58, 0xa8, 0x56, 0xf3, 0x31, 0xa5, 0x98, 0x1a, 0xda, 0xe8, 0xb1, 0xb1, 0x93, 0xd3,
	0xf4, 0x20, 0x34, 0x01, 0x44, 0xdb, 0x0b, 0x02, 0x9e, 0x4a, 0xd0, 0x76, 0x68, 0x9e, 0x71, 0xf3,
	0xa2, 0x4e, 0x68, 0x5e, 0xda, 0x69, 0xb8, 0x37, 0x2b, 0x39, 0x79, 0x65, 0xb4, 0x86, 0xeb, 0x28,
	0x70, 0xd9, 0xcd, 0x4a, 0xfc, 0xa3, 0x72, 0xb8, 0x5f, 0x7d, 0x38, 0xfe, 0xbd, 0xd7, 0xaa, 0x2a,
	0x9c, 0xc3, 0xa2, 0x6b, 0xf0, 0x1f, 0x4d, 0x37, 0xd6, 0x5d, 0x6f, 0x0d, 0xb9, 0x56, 0xcd, 0xa1,
	0xb6, 0xb7, 0x85, 0xfd, 0x5d, 0x8b, 0x62, 0x7f, 0x0b, 0xfb, 0xd4, 0x38, 0x2a, 0x88, 0xfe, 0x5e,
	0x3b, 0x08, 0xcd, 0x7e, 0x88, 0xb6, 0x3f, 0x27, 0xf4, 0xa6, 0x08, 0x59, 0x8e, 0xf0, 0x76, 0x68,
	0x9e, 0x5b, 0x4f, 0x64, 0x5e, 0x40, 0x6c, 0x1c, 0x03, 0x9d, 0xd0, 0x7c, 0x56, 0x10, 0x56, 0xa1,
	0x0a, 0xde, 0xed, 0xfd, 0xea, 0x80, 0x4a, 0xb5, 0xb3, 0x5f, 0x55, 0x37, 0x90, 0x0f, 0x54, 0xc5,
	0x0d, 0x0e, 0x46, 0x86, 0xb3, 0x49, 0x50, 0xb1, 0x1c, 0x7c, 0xaa, 0x0a, 0x18, 0x13, 0xb4, 0xe6,
	0xe2, 0x9a, 0x71, 0x6c, 0x54, 0x1b, 0x7b, 0x64, 0xfa, 0x3d, 0x1e, 0xf0, 0xd9, 0xd4, 0xe3, 0xcb,
	0x11, 0x58, 0x8e, 0x36, 0x06, 0x3a, 0xa1, 0xf9, 0xb4, 0x22, 0xda, 0x18, 0x95, 0xc2, 0x65, 0x7e,
	0x80, 0x79, 0xac, 0x5d, 0xdc, 0x74, 0x03, 0x0e, 0xf7, 0xab, 0x0f, 0x71, 0xd3, 0xbd, 0x56, 0xb5,
	0x44, 0xaa, 0x14, 0x66, 0x2c, 0x07, 0x1f, 0x6b, 0xfa, 0x90, 0xeb, 0xd9, 0xca, 0x28, 0x1f, 0x12,
	0x51, 0xfe, 0x9c, 0x47, 0x79, 0x66, 0x81, 0xeb, 0xe4, 0x82, 0x1c, 0x70, 0x63, 0x51, 0x21, 0xc6,
	0xa7, 0xa2, 0x29, 0xa8, 0x00, 0x15, 0x21, 0xaa, 0x9d, 0x74, 0x91, 0x4b, 0x01, 0x16, 0xf9, 0xc0,
	0x73, 0xc2, 0xa0, 0x14, 0xde, 0xdf, 0x35, 0xbd, 0x3f, 0x0a, 0x0f, 0xc5, 0xbe, 0xac, 0xa6, 0xe7,
	0x33, 0xe3, 0xf8, 0xa8, 0x36, 0x76, 0x7c, 0xfa, 0xc7, 0x3c, 0xb4, 0x9e, 0xc4, 0xd5, 0x92, 0xe7,
	0xb3, 0x76, 0x68, 0xf6, 0xe5, 0x9a, 0xe6, 0xc2, 0x4e, 0x68, 0x3e, 0x59, 0x0e, 0x8a, 0x23, 0x52,
	0x44, 0x93, 0x13, 0xe3, 0x93, 0x9f, 0xa9, 0x1c, 0x86, 0xe6, 0x31, 0x87, 0xb0, 0xf6, 0x7e, 0x55,
	0xe1, 0x46, 0x25, 0x3c, 0xdc, 0xaf, 0x1e, 0x17, 0xa6, 0x7b, 0xad, 0x6a, 0x8e, 0x09, 0x2c, 0xeb,
	0x82, 0x6f, 0x1c, 0xd5, 0x47, 0x0b, 0xd1, 0x34, 0x02, 0x97, 0x39, 0x36, 0xa2, 0x2c, 0xc9, 0x1b,
	0xc6, 0x89, 0x51, 0x6d, 0xec, 0xe4, 0xf4, 0x1f, 0x79, 0x68, 0xbd, 0x89, 0xc3, 0xc5, 0x19, 0xbe,
	0x92, 0xdb, 0xa1, 0xd9, 0x9f, 0x73, 0x1a, 0x89, 0x3b, 0xa1, 0x79, 0xbd, 0x1c, 0x5e, 0x84, 0x49,
	0x01, 0x7e, 0xa9, 0x5e, 0x9f, 0x98, 0xbc, 0x79, 0xf3, 0xc6, 0xd5, 0x1b, 0xd7, 0xbe, 0x7c, 0x33,
	0x8a, 0xb6, 0xbd, 0x5f, 0x55, 0x3a, 0x54, 0x8b, 0x0f, 0xf7, 0xab, 0xa0, 0xec, 0x64, 0xaf, 0x55,
	0x2d, 0xd0, 0x84, 0x8f, 0xe5, 0x8d, 0x93, 0x08, 0xe3, 0x64, 0x04, 0xee, 0xe8, 0xa7, 0x1b, 0x68,
	0xc7, 0xa2, 0x98, 0xd4, 0xac, 0xcd, 0xb5, 0x26, 0x35, 0x1e, 0x16, 0x83, 0xf9, 0x4c, 0x3b, 0x34,
	0x4f, 0x35, 0xd0, 0xce, 0x32, 0x26, 0xb5, 0x5b, 0x6b, 0x4d, 0x9e, 0x5c, 0xfa, 0x44, 0x58, 0x92,
	0x2c, 0x19, 0x1f, 0x28, 0x2b, 0x26, 0x0e, 0x7d, 0x6c, 0x6f, 0x45, 0x0e, 0x1f, 0xc9, 0x39, 0x84,
	0xd8, 0xde, 0x2a, 0x3a, 0x4c, 0x64, 0x39, 0x87, 0x89, 0x10, 0xfc, 0x41, 0xd3, 0x87, 0x7c, 0x6c,
	0x7b, 0x84, 0x60, 0x9b, 0xa7, 0x77, 0xcb, 0x21, 0x0c, 0xfb, 0x5b, 0xc8, 0xb5, 0xa8, 0x71, 0x52,
	0xf8, 0xfe, 0x9a, 0x48, 0xea, 0x89, 0xca, 0x7c, 0x0c, 0x2f, 0xf3, 0xdc, 0x21, 0x1b, 0xa6, 0x40,
	0x27, 0x34, 0xc7, 0x44, 0xdb, 0x4a, 0x54, 0x1a, 0xa5, 0xeb, 0xe3, 0x09, 0xa5, 0xc3, 0xfd, 0xea,
	0xd1, 0xeb, 0xe3, 0x22, 0xbf, 0x97, 0xda, 0x81, 0xea, 0x56, 0x40, 0x5d, 0xef, 0xf5, 0xb1, 0x8b,
	0x76, 0x69, 0x9a, 0x03, 0x74, 0x91, 0x03, 0x5e, 0x6a, 0x87, 0xe6, 0xe9, 0x08, 0xc9, 0x16, 0x7a,
	0x25, 0x26, 0x24, 0x49, 0x8b, 0x2b, 0x3c, 0x59, 0xb1, 0x30, 0x6f, 0x0c, 0xde, 0x3e, 0xaa, 0x0f,
	0xc7, 0x0d, 0xa5, 0x44, 0xb2, 0x4e, 0x6a, 0x18, 0xa7, 0x44, 0x27, 0xfd, 0x85, 0xcf, 0xe1, 0x21,
	0xc8, 0xf5, 0x4a, 0x21, 0x2c, 0xb6, 0x43, 0x73, 0xc8, 0x57, 0x43, 0x69, 0xa2, 0xed, 0x82, 0x4b,
	0x2c, 0x27, 0xc6, 0xa5, 0x25, 0xdb, 0xd5, 0x5f, 0x77, 0x88, 0x77, 0xf2, 0x04, 0xef, 0xe4, 0x6e,
	0x34, 0xa1, 0x11, 0xc5, 0x59, 0x46, 0xc0, 0x9a, 0x7e, 0x9a, 0x32, 0xe4, 0x33, 0x6b, 0xcd, 0xf7,
	0xb6, 0x29, 0xf6, 0x8d, 0x1e, 0xd1, 0xd7, 0x2f, 0xb6, 0x43, 0xb3, 0x47, 0x00, 0xd3, 0x91, 0xbc,
	0x13, 0x9a, 0x8f, 0x8b, 0x70, 0x64, 0x61, 0xd7, 0x9e, 0xce, 0x99, 0x82, 0x5f, 0x6a, 0xfa, 0x39,
	0x82, 0x98, 0xc5, 0x7c, 0xc4, 0x77, 0x35, 0xe4, 0xa6, 0x03, 0xdb, 0x2b, 0x1a, 0x7b, 0xfd, 0x20,
	0x34, 0xf5, 0xdb, 0x53, 0x2b, 0x59, 0x5a, 0xd7, 0x09, 0x62, 0xd9, 0x18, 0x9b, 0xa2, 0xe1, 0x4c,
	0xa4, 0x48, 0xe1, 0xb2, 0x41, 0xee, 0x4b, 0x4a, 0xd7, 0x52, 0x13, 0xb0, 0x9f, 0x20, 0xb6, 0x92,
	0xd0, 0x49, 0x26, 0xc4, 0x9f, 0x4a, 0x3c, 0x5d, 0x8c, 0x28, 0xb6, 0x1a, 0xc6, 0x19, 0x31, 0x15,
	0xbe, 0xc5, 0xa7, 0xc2, 0xc9, 0xdb, 0x53, 0x2b, 0x0b, 0x5c, 0xcc, 0x07, 0xff, 0x0c, 0x41, 0x2c,
	0xfa, 0x70, 0x48, 0xc0, 0x44, 0xf1, 0x53, 0x49, 0xc8, 0xca, 0x72, 0xe5, 0xda, 0x68, 0xef, 0x57,
	0x4b, 0xf6, 0x65, 0x51, 0xba, 0x82, 0xb2, 0x86, 0x21, 0x90, 0xd9, 0x47, 0x32, 0xf0, 0x37, 0x4d,
	0x1f, 0xca, 0x93, 0xf7, 0x31, 0xc1, 0xdb, 0x62, 0x26, 0x9f, 0x15, 0xf4, 0xf7, 0x38, 0xfd, 0x53,
	0xb7, 0xa7, 0x56, 0x60, 0x04, 0xf0, 0x00, 0xfa, 0x08, 0x62, 0xc9, 0x67, 0x1a, 0x42, 0x35, 0x09,
	0x21, 0x8f, 0x48, 0x41, 0x5c, 0x95, 0x83, 0x50, 0xf8, 0x50, 0x09, 0x79, 0x20, 0x57, 0x79, 0x20,
	0x32, 0x05, 0x38, 0x20, 0x87, 0x92, 0x48, 0x15, 0xc1, 0x30, 0xa7, 0x81, 0xbd, 0x80, 0x59, 0xd4,
	0xe8, 0xcb, 0x07, 0xb3, 0x12, 0x01, 0xcb, 0x71, 0x30, 0xc9, 0x27, 0x9f, 0xe9, 0xb5, 0x5c, 0x30,
	0x79, 0xa4, 0xdb, 0xf2, 0x53, 0xf8, 0x50, 0x09, 0xd3, 0x25, 0x27, 0x53, 0xc8, 0x07, 0x93, 0x48,
	0xc1, 0x4f, 0x34, 0xdd, 0x08, 0x28, 0x5a, 0xc7, 0x96, 0x8f, 0xf9, 0xbe, 0xef, 0x90, 0x75, 0x0b,
	0xd9, 0x36, 0x6e, 0x32, 0x5c, 0x33, 0x80, 0x88, 0x06, 0xf1, 0x15, 0xb0, 0x0a, 0xa7, 0x62, 0x29,
	0x5f, 0x01, 0x81, 0x9f, 0x7c, 0x75, 0x42, 0xf3, 0xac, 0x08, 0x22, 0x13, 0x49, 0x84, 0x65, 0xc5,
	0xdc, 0x17, 0x9f, 0xf1, 0x99, 0x4b, 0x38, 0x28, 0x28, 0xc0, 0x84, 0x41, 0x22, 0x07, 0x6f, 0xea,
	0x03, 0x45, 0x72, 0x14, 0x63, 0x62, 0xf4, 0x0b, 0x62, 0xf3, 0x07, 0xa1, 0x79, 0x62, 0x15, 0x2e,
	0x63, 0x4c, 0xda, 0xa1, 0x79, 0x22, 0xf0, 0xf9, 0xaf, 0x4e, 0x68, 0xf6, 0xc4, 0x84, 0xf8, 0xa7,
	0x44, 0x26, 0x51, 0x48, 0x7f, 0xed, 0xb5, 0xaa, 0xb1, 0x39, 0x04, 0x79, 0x02, 0x5c, 0x06, 0x7e,
	0xa0, 0xe9, 0x8f, 0x16, 0x5b, 0x0f, 0x88, 0xf3, 0x7a, 0x80, 0x2d, 0xa7, 0x66, 0x0c, 0x88, 0x22,
	0xe2, 0xb5, 0xa8, 0x6f, 0x56, 0x85, 0x78, 0x7e, 0x36, 0xea, 0x9b, 0xf8, 0x4b, 0xee, 0x9b, 0x44,
	0xa1, 0x12, 0x75, 0x4a, 0xf2, 0xd9, 0x91, 0xbf, 0xe2, 0x4e, 0x49, 0xb0, 0x62, 0xa7, 0x24, 0x5a,
	0xe0, 0x43, 0x4d, 0xef, 0x2f, 0xf1, 0xf2, 0x5d, 0xe3, 0x9c, 0x60, 0xf4, 0x1d, 0x3e, 0xf7, 0x8e,
	0xaf, 0xc2, 0x55, 0xb8, 0xd0, 0x0e, 0xcd, 0xe3, 0x81, 0xbf, 0x0a, 0x17, 0x3a, 0xa1, 0x79, 0x23,
	0x21, 0x02, 0x17, 0xa4, 0xd9, 0xb5, 0xc1, 0x58, 0x93, 0xde, 0xbc, 0x72, 0xa5, 0x86, 0x18, 0xba,
	0x4c, 0x77, 0x89, 0xcd, 0x36, 0xf8, 0x41, 0x8d, 0x60, 0x76, 0x85, 0xe0, 0x6d, 0x2e, 0xe5, 0x84,
	0x63, 0x27, 0xc9, 0x8f, 0xc3, 0xfd, 0xea, 0x03, 0x18, 0xee, 0xb5, 0xaa, 0x11, 0x0b, 0xd8, 0x57,
	0x88, 0xc3, 0x77, 0xc1, 0xbf, 0x35, 0xdd, 0x2c, 0x86, 0xd0, 0xf4, 0x28, 0xdf, 0xe1, 0x28, 0xb6,
	0x03, 0x1f, 0xbb, 0xbb, 0xc6, 0xa0, 0x48, 0xbf, 0x3f, 0x12, 0x27, 0x88, 0x55, 0xb8, 0xe4, 0x51,
	0x36, 0x9f, 0x82, 0xed, 0xd0, 0x3c, 0x1b, 0xf8, 0x79, 0x59, 0x27, 0x34, 0x9f, 0x88, 0x83, 0xcc,
	0x03, 0x52, 0xbc, 0x75, 0xe4, 0x52, 0x91, 0x92, 0xcb, 0xd6, 0x0a, 0x19, 0xaf, 0x3c, 0x85, 0x05,
	0x3f, 0x2f, 0x14, 0x29, 0xc0, 0x0b, 0xf9, 0xb0, 0xf2, 0x28, 0xf8, 0x97, 0x22, 0x42, 0x87, 0x38,
	0xcc, 0xe1, 0xe7, 0x08, 0xbe, 0xdf, 0x59, 0xd4, 0x18, 0x12, 0xb3, 0xf8, 0x87, 0xe2, 0xf4, 0xb0,
	0x0a, 0xe7, 0x23, 0x74, 0x96, 0x83, 0x3c, 0x61, 0x9c, 0x09, 0xfc, 0x9c, 0x28, 0x4d, 0x17, 0x05,
	0xb9, 0x9c, 0x2c, 0x6e, 0x8c, 0xe7, 0x12, 0x78, 0xd1, 0x43, 0x59, 0xc4, 0x77, 0x20, 0x6e, 0xc5,
	0x0f, 0x0c, 0x05, 0x0a, 0x70, 0x38, 0x1f, 0x60, 0x0e, 0x04, 0xef, 0x68, 0xfa, 0x10, 0x0a, 0x98,
	0x67, 0x05, 0xcd, 0x75, 0x1f, 0xd5, 0x70, 0x56, 0x9b, 0x6c, 0x18, 0x8f, 0x8a, 0xb8, 0x96, 0xf8,
	0x09, 0x88, 0xab, 0xac, 0x46, 0x1a, 0xc9, 0xb6, 0xfe, 0x4a, 0x7a, 0x58, 0x50, 0x81, 0x72, 0x34,
	0x93, 0x72, 0xa1, 0x36, 0x31, 0x09, 0x95, 0xde, 0x40, 0x43, 0x1f, 0x4a, 0x38, 0x30, 0xcf, 0x6a,
	0xfa, 0xbc, 0xc7, 0xc5, 0xd6, 0x48, 0x8d, 0xf3, 0x62, 0x0a, 0x5d, 0xe7, 0x44, 0x62, 0x95, 0x15,
	0x6f, 0xc9, 0xc7, 0x30, 0xc6, 0x3b, 0xa1, 0x79, 0x3e, 0xea, 0x51, 0x05, 0x58, 0x81, 0x4a, 0x1b,
	0xb0, 0xa5, 0x83, 0x4d, 0x8c, 0x9b, 0x16, 0xc3, 0x8d, 0xa6, 0xe7, 0x23, 0xdf, 0xc1, 0xd4, 0xda,
	0x30, 0x86, 0x45, 0xc8, 0xaf, 0xf0, 0x79, 0xc9, 0xd1, 0x95, 0x0c, 0xe4, 0xe1, 0x5e, 0x14, 0xad,
	0x14, 0x01, 0xf9, 0x68, 0x74, 0x4d, 0x0e, 0x75, 0xf2, 0x1a, 0x2c, 0x79, 0x01, 0xbb, 0x7a, 0xbf,
	0x8d, 0xec, 0x0d, 0x6c, 0x39, 0xeb, 0xc4, 0xf3, 0x71, 0xcd, 0xaa, 0x3b, 0x2e, 0xa6, 0xc6, 0x05,
	0x11, 0xe2, 0x3c, 0xdf, 0x60, 0x04, 0x3c, 0x1f, 0xa1, 0x73, 0x1c, 0x4c, 0x3b, 0xba, 0x84, 0x94,
	0x96, 0x44, 0x3a, 0xd5, 0x61, 0xd9, 0x0d, 0xf8, 0x9e, 0xa6, 0x9f, 0x6f, 0xfa, 0xde, 0x3a, 0x3f,
	0x5b, 0x58, 0x41, 0xb3, 0x86, 0x18, 0x96, 0xeb, 0xf5, 0xc7, 0x44, 0xec, 0x2b, 0xbc, 0xdc, 0x4c,
	0xb4, 0x56, 0x85, 0x92, 0x5c, 0x9b, 0x47, 0x67, 0xde, 0x2e, 0xb8, 0x44, 0xe7, 0x79, 0xa9, 0x23,
	0xb4, 0xe7, 0x61, 0x37, 0x8f, 0xe0, 0x6d, 0x4d, 0x1f, 0x74, 0x9d, 0x86, 0xc3, 0xac, 0x35, 0x44,
	0x6a, 0xdb, 0x4e, 0x8d, 0x6d, 0x58, 0x0e, 0xb1, 0x5c, 0x44, 0x8c, 0x11, 0xd1, 0x25, 0x8b, 0xe2,
	0x2c, 0xc7, 0x35, 0xa6, 0x13, 0x85, 0x79, 0xb2, 0x80, 0x48, 0x76, 0xfe, 0x2e, 0x63, 0xf7, 0xe8,
	0x16, 0x95, 0x2b, 0xf0, 0x96, 0xa6, 0x83, 0x86, 0x43, 0xac, 0x0d, 0xaf, 0x81, 0xad, 0x9a, 0x43,
	0x37, 0xad, 0xba, 0x8f, 0xb1, 0x61, 0x8e, 0x6a, 0x63, 0xa7, 0x26, 0x7b, 0x2e, 0x47, 0x17, 0x5d,
	0x97, 0x97, 0x9d, 0x37, 0xf0, 0xf4, 0xcb, 0x1f, 0x85, 0xe6, 0x11, 0xbe, 0xaa, 0x1b, 0x0e, 0x79,
	0xc5, 0x6b, 0xe0, 0x59, 0x87, 0x6e, 0xce, 0xf9, 0x18, 0xa7, 0xb3, 0xa3, 0x20, 0x97, 0xd7, 0xc1,
	0xe8, 0x25, 0x4e, 0xe4, 0xd8, 0xc4, 0xe8, 0x25, 0x58, 0x34, 0x07, 0x77, 0x35, 0xbd, 0x27, 0x99,
	0xef, 0x62, 0x17, 0x18, 0x15, 0xbb, 0xc0, 0x9f, 0x45, 0x05, 0x92, 0x4c, 0xda, 0x68, 0x2f, 0x38,
	0xe5, 0x67, 0x9f, 0x9d, 0xd0, 0x9c, 0x4d, 0x0e, 0x00, 0x89, 0x4c, 0xb1, 0x2f, 0xc4, 0x2b, 0x80,
	0x16, 0x52, 0x7c, 0x03, 0x33, 0x74, 0xf9, 0x2b, 0xd4, 0x23, 0x3c, 0x95, 0xe6, 0xdc, 0xe6, 0x3f,
	0x0f, 0xf7, 0xab, 0x63, 0x0f, 0xea, 0x8a, 0x97, 0x2b, 0x12, 0x5f, 0x98, 0xf9, 0xf1, 0x5d, 0xf0,
	0x05, 0xbd, 0x0f, 0xb9, 0xdb, 0xfc, 0x30, 0x14, 0x1d, 0xee, 0x09, 0x66, 0xd4, 0x78, 0x5c, 0xdc,
	0xa9, 0xf1, 0x33, 0xe8, 0x99, 0x08, 0x14, 0x87, 0xe4, 0xdb, 0x98, 0xf1, 0x89, 0x3f, 0x10, 0x65,
	0x98, 0x9c, 0xbc, 0x02, 0x8b, 0x8a, 0xe0, 0x7f, 0x9a, 0x3e, 0xe6, 0x6d, 0x61, 0x7f, 0xdb, 0x77,
	0x18, 0x4f, 0x1c, 0x0d, 0x8f, 0x61, 0xab, 0x86, 0xb7, 0x1c, 0x1b, 0x5b, 0x04, 0x35, 0x30, 0xb5,
	0x3c, 0x62, 0xc5, 0xe7, 0x12, 0xa3, 0x92, 0xdd, 0xf6, 0x0c, 0xdd, 0x49, 0x8c, 0xa0, 0xb0, 0x99,
	0xc5, 0x5b, 0xb7, 0xb9, 0x7a, 0x3b, 0x34, 0x2f, 0x7a, 0x25, 0xc8, 0xb1, 0xb1, 0x40, 0xef, 0x90,
	0x99, 0xc8, 0x55, 0x27, 0x34, 0x5f, 0x10, 0x04, 0x1f, 0x40, 0xb7, 0xfb, 0xa4, 0xe4, 0x87, 0xaa,
	0x2e, 0x3c, 0xe0, 0x83, 0xb0, 0x00, 0x5f, 0xd7, 0xcf, 0xf1, 0x34, 0x66, 0x39, 0xa4, 0x86, 0x77,
	0x2c, 0x3e, 0x93, 0xd7, 0x5c, 0xcf, 0xde, 0xa4, 0xc6, 0x45, 0xb1, 0xa4, 0xf9, 0xa4, 0x01, 0x5c,
	0x61, 0x9e, 0xe3, 0x8b, 0x0e, 0x99, 0x16, 0x68, 0x7a, 0x89, 0x5a, 0x86, 0x94, 0x85, 0x6b, 0x54,
	0x8e, 0x42, 0x85, 0x27, 0xf0, 0x4f, 0x5e, 0x7d, 0x12, 0x64, 0x6f, 0xe2, 0x9a, 0x45, 0x3c, 0xe6,
	0xd4, 0x1d, 0x1b, 0x45, 0xd7, 0x01, 0x35, 0x6a, 0x54, 0xc5, 0xf8, 0xbe, 0xcb, 0xbb, 0x7b, 0x70,
	0x35, 0x52, 0xba, 0x2d, 0xe9, 0xcc, 0xcf, 0xf2, 0xde, 0x1e, 0x0c, 0x94, 0x48, 0x27, 0x34, 0x87,
	0xa3, 0xd4, 0xae, 0x82, 0xc5, 0xd5, 0xa1, 0x12, 0xe9, 0xec, 0x57, 0xbb, 0x78, 0xdc, 0x6b, 0x55,
	0xbb, 0xb0, 0x80, 0x4a, 0x8b, 0x1a, 0x05, 0x50, 0x3f, 0xcd, 0x7c, 0x54, 0xaf, 0x3b, 0xb6, 0x65,
	0xbb, 0x88, 0x52, 0xe3, 0x92, 0xe8, 0xd6, 0xe7, 0xf8, 0xf1, 0x35, 0x06, 0x66, 0xb8, 0xbc, 0x13,
	0x9a, 0x20, 0xea, 0x50, 0x49, 0x98, 0xde, 0x9b, 0xe4, 0x54, 0xc1, 0x9b, 0x7a, 0x7f, 0xdc, 0xc5,
	0x56, 0xdd, 0x73, 0x6b, 0xd8, 0xb7, 0x9a, 0x88, 0x6d, 0x18, 0x4f, 0x88, 0x55, 0x7f, 0xeb, 0x20,
	0x34, 0x87, 0x67, 0x71, 0xd3, 0xc7, 0x36, 0x62, 0xb8, 0x36, 0x1b, 0x29, 0xce, 0x09, 0xbd, 0x25,
	0xc4, 0x36, 0xda, 0xa1, 0xa9, 0x3d, 0x97, 0x1e, 0x96, 0x6b, 0x45, 0xf8, 0x59, 0xaf, 0xe1, 0xf0,
	0x41, 0x62, 0xbb, 0x15, 0x43, 0x83, 0x7d, 0x25, 0x1c, 0x6c, 0xea, 0x67, 0x29, 0x66, 0x96, 0xeb,
	0x6d, 0x5b, 0x4d, 0xdf, 0xf1, 0x7c, 0x87, 0xed, 0x1a, 0x4f, 0x8a, 0x45, 0x31, 0xd5, 0x0e, 0xcd,
	0x5e, 0x8a, 0xd9, 0x82, 0xb7, 0xbd, 0x14, 0x23, 0x69, 0x66, 0xcb, 0x8b, 0xbb, 0x1e, 0xcb, 0x0b,
	0xe6, 0xe0, 0x3d, 0x4d, 0x1f, 0x6c, 0xa0, 0x9d, 0x24, 0x4c, 0xdb, 0x23, 0x76, 0xe0, 0xfb, 0x98,
	0xd8, 0xbb, 0xc6, 0x98, 0xe8, 0x47, 0x2a, 0xee, 0x3e, 0xd0, 0xf6, 0x22, 0xda, 0x89, 0x38, 0xce,
	0x64, 0x2a, 0x7c, 0xcb, 0x6f, 0x28, 0xe4, 0xe9, 0x96, 0xaf, 0x02, 0x93, 0x2e, 0x17, 0x97, 0x15,
	0x6a, 0xbf, 0x50, 0xe9, 0x15, 0x7c, 0xac, 0xe9, 0xfd, 0xb6, 0x8f, 0xe8, 0x46, 0xa1, 0x24, 0x7f,
	0x4a, 0x0c, 0xcb, 0xfb, 0xa2, 0x24, 0x9f, 0x49, 0x4a, 0x72, 0x3b, 0x2e, 0xc9, 0xe7, 0xa2, 0xbd,
	0x99, 0x9b, 0x65, 0xc5, 0xb1, 0x32, 0x0d, 0x0b, 0x9d, 0x72, 0x99, 0x2d, 0xc4, 0x7c, 0x2e, 0xf7,
	0x95, 0x9c, 0xf0, 0x62, 0xdd, 0x8e, 0x8b, 0xf5, 0xea, 0x83, 0xb8, 0xe1, 0xe5, 0xfa, 0x4c, 0x54,
	0xae, 0x17, 0x9c, 0xf9, 0x2e, 0xf8, 0x99, 0xa6, 0x0f, 0x15, 0xc3, 0x4b, 0x6e, 0x49, 0x9e, 0x16,
	0xe3, 0xef, 0x1c, 0x84, 0xe6, 0xc9, 0x19, 0x28, 0x5d, 0xf0, 0xe7, 0xbd, 0x14, 0x2f, 0xf8, 0x95,
	0x68, 0xb7, 0xa9, 0xb1, 0xd7, 0xaa, 0x66, 0xbe, 0xa1, 0xda, 0x33, 0xf8, 0xa6, 0xa6, 0x0f, 0x52,
	0x16, 0x10, 0x8b, 0x57, 0x4e, 0xc8, 0x75, 0xb6, 0xb0, 0x15, 0xdd, 0x1d, 0x51, 0xe3, 0x99, 0xb4,
	0x1e, 0xed, 0xe7, 0x1a, 0xb7, 0x12, 0x85, 0x65, 0x8e, 0x2f, 0xa7, 0x55, 0x92, 0x02, 0xcb, 0xd7,
	0xd6, 0x52, 0x42, 0x3b, 0x36, 0x71, 0x63, 0x1c, 0xaa, 0xbc, 0xf1, 0x23, 0x6b, 0x81, 0x06, 0xcf,
	0xab, 0xd4, 0x78, 0x56, 0x90, 0x78, 0x95, 0x17, 0x6a, 0x39, 0xb3, 0x45, 0x87, 0x64, 0xa5, 0x7d,
	0x09, 0x91, 0x6b, 0xc4, 0x5c, 0x42, 0x9d, 0x1c, 0x87, 0x65, 0x3f, 0xbc, 0x2a, 0xef, 0x11, 0xad,
	0x27, 0xef, 0x4e, 0xcf, 0x89, 0x1c, 0x5a, 0x3b, 0x08, 0xcd, 0x5e, 0x88, 0xb6, 0x97, 0x59, 0x20,
	0xbd, 0x38, 0x9d, 0xa2, 0xd9, 0x67, 0x7a, 0x37, 0x94, 0xc9, 0xee, 0xfb, 0x2a, 0x56, 0xf0, 0x08,
	0x65, 0x7f, 0x60, 0x4b, 0x3f, 0xc3, 0x4f, 0x81, 0x6b, 0x88, 0x62, 0x2b, 0x7a, 0xfe, 0x33, 0x2e,
	0x8f, 0x6a, 0x63, 0xbd, 0x93, 0xbd, 0x49, 0x59, 0xb4, 0x22, 0xa4, 0xe2, 0x32, 0xaf, 0x37, 0x51,
	0x8d, 0x64, 0x69, 0xe6, 0xc8, 0x8b, 0x2b, 0xa3, 0x3e, 0x16, 0x43, 0x1a, 0x4f, 0x8f, 0xb7, 0x5a,
	0x55, 0x0d, 0x16, 0x4c, 0xc1, 0xf7, 0x8f, 0xea, 0x17, 0x79, 0xd6, 0x48, 0xd3, 0x05, 0x3f, 0x53,
	0xda, 0x5e, 0x83, 0x4f, 0x59, 0x1f, 0xbf, 0x1e, 0x60, 0xca, 0xac, 0x4d, 0x67, 0xcd, 0xb8, 0x22,
	0x86, 0xe3, 0xaf, 0x5a, 0xfc, 0x74, 0xb8, 0x88, 0x76, 0x66, 0xe6, 0x61, 0x84, 0xdf, 0x72, 0xa6,
	0xdb, 0xa1, 0x69, 0x36, 0xd0, 0x4e, 0xba, 0xc4, 0xd9, 0x7c, 0xec, 0x23, 0x53, 0x49, 0x77, 0xc1,
	0xfb, 0xe8, 0x49, 0xe7, 0xb1, 0xfb, 0xba, 0xbc, 0xbf, 0x4a, 0xfc, 0x18, 0x59, 0xa0, 0x0b, 0xef,
	0x63, 0xb6, 0x06, 0x3e, 0xd5, 0xf4, 0xc1, 0xf4, 0x45, 0xc4, 0x45, 0xf2, 0x1b, 0xea, 0xb8, 0x58,
	0xc0, 0x1f, 0xf0, 0x9e, 0x18, 0x48, 0x5e, 0x14, 0x16, 0xa6, 0x6e, 0xcb, 0xcf, 0xa8, 0x03, 0x48,
	0x21, 0x4f, 0x0b, 0x69, 0x15, 0xa8, 0x7a, 0xc8, 0x52, 0x3a, 0xe9, 0x22, 0x97, 0x96, 0xbe, 0x92,
	0x14, 0xcc, 0xac, 0x90, 0xf4, 0x06, 0xbb, 0xa5, 0x9f, 0x17, 0x8f, 0x1e, 0xf5, 0xc0, 0x75, 0xe3,
	0xaa, 0xc6, 0x23, 0xc9, 0x11, 0xd5, 0x98, 0x10, 0x91, 0xde, 0xe4, 0x55, 0x03, 0xd7, 0x9a, 0x0b,
	0x5c, 0x57, 0xd4, 0x23, 0x77, 0x48, 0x7c, 0xa8, 0xec, 0x84, 0xe6, 0x85, 0x78, 0xcb, 0x52, 0xc1,
	0x15, 0xd8, 0xc5, 0x0e, 0xbc, 0xaa, 0x9f, 0xae, 0x63, 0xc4, 0x02, 0x1f, 0x5b, 0x75, 0x17, 0xad,
	0x53, 0x63, 0x52, 0xac, 0xbb, 0x4b, 0x7c, 0xa7, 0x8f, 0x81, 0x39, 0x2e, 0x4f, 0x1f, 0x48, 0x24,
	0x61, 0x05, 0xe6, 0x54, 0xc0, 0xb6, 0x3e, 0x24, 0xbd, 0x8b, 0x44, 0x67, 0x1c, 0x4c, 0xbc, 0x60,
	0x7d, 0xc3, 0xb8, 0x2a, 0x26, 0xed, 0x4b, 0x22, 0xbd, 0xa6, 0x2a, 0x0b, 0x5c, 0xe3, 0x65, 0xa1,
	0x90, 0x56, 0x3d, 0x4a, 0x34, 0xad, 0x28, 0xd4, 0xc6, 0x60, 0x53, 0x1f, 0x28, 0x35, 0xdc, 0x40,
	0x3b, 0xc6, 0x35, 0xd1, 0xea, 0x0b, 0xbc, 0x18, 0x2c, 0x18, 0x2e, 0xa2, 0x9d, 0x4e, 0x68, 0x1a,
	0xaa, 0x26, 0x17, 0xd1, 0x4e, 0xda, 0x9e, 0xc2, 0x0c, 0xbc, 0x73, 0x54, 0x37, 0x93, 0xcb, 0x1e,
	0x0b, 0xb9, 0xbc, 0xa4, 0xf0, 0xdc, 0x9a, 0xc5, 0x5c, 0x6a, 0xf1, 0xfc, 0xe1, 0x78, 0x84, 0x1a,
	0xcf, 0x8b, 0xf1, 0xfa, 0x90, 0xcf, 0xcc, 0xe1, 0xe4, 0x6a, 0x65, 0x8a, 0xab, 0xde, 0x71, 0x6b,
	0x2b, 0x0b, 0xcb, 0x9f, 0x8f, 0xf5, 0xda, 0xa1, 0x39, 0xec, 0x74, 0x87, 0xd3, 0x7a, 0xe7, 0x1e,
	0x3a, 0x7c, 0x7e, 0xde, 0xd3, 0xc7, 0xbd, 0xe1, 0xbd, 0x56, 0xf5, 0x5e, 0x04, 0x61, 0xd9, 0xd6,
	0xa5, 0x09, 0x08, 0xbe, 0xaa, 0xf7, 0x04, 0x4d, 0xd2, 0x4c, 0x37, 0xd4, 0x5f, 0xcd, 0x89, 0xb0,
	0xbf, 0x78, 0x10, 0x9a, 0xe7, 0xb2, 0x5a, 0x6e, 0x75, 0x89, 0x2c, 0x65, 0xbb, 0xab, 0xa8, 0xe2,
	0xe2, 0x02, 0xb7, 0x49, 0x9a, 0x31, 0x20, 0xd5, 0x6f, 0x7b, 0xad, 0xaa, 0xda, 0xd8, 0xd0, 0xe0,
	0x29, 0xc9, 0x04, 0xfc, 0x42, 0x8b, 0x9b, 0x4f, 0x5e, 0x13, 0xde, 0x9b, 0x13, 0xc3, 0xfd, 0x96,
	0xc8, 0x07, 0x79, 0x17, 0xe9, 0xcb, 0x82, 0x68, 0x7e, 0x34, 0x6d, 0x5e, 0x7e, 0x11, 0x90, 0x38,
	0x64, 0x89, 0xef, 0x7c, 0x77, 0x2d, 0xbe, 0xc0, 0x55, 0xad, 0x18, 0x1a, 0xd4, 0x33, 0x2b, 0xf0,
	0x3b, 0x4d, 0xef, 0x15, 0x34, 0xb3, 0x77, 0x83, 0x5f, 0x47, 0x44, 0xbf, 0x2d, 0xce, 0x07, 0x79,
	0x17, 0xd2, 0x1b, 0x82, 0xa0, 0x5a, 0x49, 0xa9, 0xe6, 0x6f, 0xfd, 0x95, 0x64, 0x2f, 0xdc, 0x4b,
	0x8f, 0x9f, 0x02, 0xd4, 0x6d, 0x19, 0x1a, 0xec, 0x91, 0x2d, 0x33, 0xca, 0xd9, 0xeb, 0xc0, 0xfb,
	0xdd, 0x29, 0x4b, 0x2f, 0x05, 0x05, 0xca, 0xf9, 0xbb, 0xfd, 0xee, 0x94, 0xbb, 0xe9, 0x95, 0x29,
	0x27, 0x9a, 0x09, 0xe5, 0xf4, 0x31, 0xa0, 0xae, 0x47, 0xaf, 0x90, 0x69, 0xf9, 0xf0, 0x9b, 0x39,
	0x91, 0xc7, 0x3e, 0x9b, 0xe7, 0x2b, 0x1e, 0xf2, 0xb2, 0x3a, 0x42, 0x9a, 0x8c, 0x7e, 0x86, 0xe4,
	0x0f, 0x13, 0x3d, 0x12, 0x42, 0xc5, 0xe5, 0x4d, 0xf9, 0xde, 0xc4, 0x6a, 0xda, 0xcc, 0xf8, 0x80,
	0x77, 0x91, 0x36, 0xbd, 0x78, 0x10, 0x9a, 0x17, 0xb2, 0x16, 0x17, 0xf3, 0xb7, 0x1e, 0x4b, 0x36,
	0xcb, 0xf7, 0x53, 0xa3, 0x84, 0xe7, 0x9b, 0x07, 0x65, 0x05, 0x5e, 0x2b, 0x0d, 0x14, 0x2a, 0x05,
	0x6a, 0x23, 0x42, 0x8d, 0xdf, 0x46, 0xa3, 0xb4, 0x52, 0xa0, 0x20, 0xef, 0xb0, 0xcb, 0x5c, 0xb1,
	0x40, 0xa1, 0x84, 0x97, 0x87, 0x4a, 0x30, 0x29, 0xe9, 0x4d, 0xbf, 0xf8, 0xd1, 0x27, 0x23, 0x47,
	0x5a, 0x9f, 0x8c, 0x1c, 0xf9, 0xe8, 0x60, 0x44, 0x6b, 0x1d, 0x8c, 0x68, 0xdf, 0xbd, 0x3b, 0x72,
	0xe4, 0xdd, 0xbb, 0x23, 0x5a, 0xeb, 0xee, 0xc8, 0x91, 0x7f, 0xdc, 0x1d, 0x39, 0xf2, 0xda, 0xf0,
	0xba, 0xc3, 0x36, 0x82, 0xb5, 0xcb, 0xb6, 0xd7, 0xb8, 0x82, 0x77, 0x9a, 0xeb, 0xde, 0x15, 0x5e,
	0xbb, 0x47, 0x85, 0xd4, 0xda, 0x09, 0xf1, 0xcf, 0xa9, 0xab, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0xd7, 0x00, 0x06, 0x90, 0x99, 0x25, 0x00, 0x00,
}

func (m *OptionsConfiguration) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OptionsConfiguration) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OptionsConfiguration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeprecatedMaxConcurrentScans != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.DeprecatedMaxConcurrentScans))
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xb2
		i--
		dAtA[i] = 0xf0
	}
	if m.DeprecatedMinHomeDiskFreePct != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.DeprecatedMinHomeDiskFreePct))))
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xb2
		i--
		dAtA[i] = 0xe9
	}
	if len(m.DeprecatedRelayServers) > 0 {
		for iNdEx := len(m.DeprecatedRelayServers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.DeprecatedRelayServers[iNdEx])
			copy(dAtA[i:], m.DeprecatedRelayServers[iNdEx])
			i = encodeVarintOptionsconfiguration(dAtA, i, uint64(len(m.DeprecatedRelayServers[iNdEx])))
			i--
			dAtA[i] = 0x4
			i--
			dAtA[i] = 0xb2
			i--
			dAtA[i] = 0xe2
		}
	}
	if m.DeprecatedUPnPTimeoutS != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.DeprecatedUPnPTimeoutS))
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xb2
		i--
		dAtA[i] = 0xd8
	}
	if m.DeprecatedUPnPRenewalM != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.DeprecatedUPnPRenewalM))
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xb2
		i--
		dAtA[i] = 0xd0
	}
	if m.DeprecatedUPnPLeaseM != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.DeprecatedUPnPLeaseM))
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xb2
		i--
		dAtA[i] = 0xc8
	}
	if m.DeprecatedUPnPEnabled {
		i--
		if m.DeprecatedUPnPEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x4
		i--
		dAtA[i] = 0xb2
		i--
		dAtA[i] = 0xc0
	}
	if m.InsecureAllowOldTLSVersions {
		i--
		if m.InsecureAllowOldTLSVersions {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xa8
	}
	if m.ConnectionLimitMax != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.ConnectionLimitMax))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0xa0
	}
	if m.ConnectionLimitEnough != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.ConnectionLimitEnough))
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0x98
	}
	if len(m.FeatureFlags) > 0 {
		for iNdEx := len(m.FeatureFlags) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FeatureFlags[iNdEx])
			copy(dAtA[i:], m.FeatureFlags[iNdEx])
			i = encodeVarintOptionsconfiguration(dAtA, i, uint64(len(m.FeatureFlags[iNdEx])))
			i--
			dAtA[i] = 0x3
			i--
			dAtA[i] = 0x92
		}
	}
	if m.SendFullIndexOnUpgrade {
		i--
		if m.SendFullIndexOnUpgrade {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0x88
	}
	if m.AnnounceLANAddresses {
		i--
		if m.AnnounceLANAddresses {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x3
		i--
		dAtA[i] = 0x80
	}
	if m.RawMaxCIRequestKiB != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.RawMaxCIRequestKiB))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xf8
	}
	if m.DatabaseTuning != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.DatabaseTuning))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xf0
	}
	if len(m.RawStunServers) > 0 {
		for iNdEx := len(m.RawStunServers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RawStunServers[iNdEx])
			copy(dAtA[i:], m.RawStunServers[iNdEx])
			i = encodeVarintOptionsconfiguration(dAtA, i, uint64(len(m.RawStunServers[iNdEx])))
			i--
			dAtA[i] = 0x2
			i--
			dAtA[i] = 0xea
		}
	}
	if m.StunKeepaliveMinS != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.StunKeepaliveMinS))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xe0
	}
	if m.StunKeepaliveStartS != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.StunKeepaliveStartS))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xd8
	}
	if m.CREnabled {
		i--
		if m.CREnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xd0
	}
	if len(m.CRURL) > 0 {
		i -= len(m.CRURL)
		copy(dAtA[i:], m.CRURL)
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(len(m.CRURL)))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xca
	}
	if m.RawMaxFolderConcurrency != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.RawMaxFolderConcurrency))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xc0
	}
	if m.SetLowPriority {
		i--
		if m.SetLowPriority {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xb8
	}
	if len(m.DeprecatedDefaultFolderPath) > 0 {
		i -= len(m.DeprecatedDefaultFolderPath)
		copy(dAtA[i:], m.DeprecatedDefaultFolderPath)
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(len(m.DeprecatedDefaultFolderPath)))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xb2
	}
	if m.TrafficClass != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.TrafficClass))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xa8
	}
	if len(m.UnackedNotificationIDs) > 0 {
		for iNdEx := len(m.UnackedNotificationIDs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.UnackedNotificationIDs[iNdEx])
			copy(dAtA[i:], m.UnackedNotificationIDs[iNdEx])
			i = encodeVarintOptionsconfiguration(dAtA, i, uint64(len(m.UnackedNotificationIDs[iNdEx])))
			i--
			dAtA[i] = 0x2
			i--
			dAtA[i] = 0xa2
		}
	}
	if m.TempIndexMinBlocks != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.TempIndexMinBlocks))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x98
	}
	if m.OverwriteRemoteDevNames {
		i--
		if m.OverwriteRemoteDevNames {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x90
	}
	if len(m.AlwaysLocalNets) > 0 {
		for iNdEx := len(m.AlwaysLocalNets) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AlwaysLocalNets[iNdEx])
			copy(dAtA[i:], m.AlwaysLocalNets[iNdEx])
			i = encodeVarintOptionsconfiguration(dAtA, i, uint64(len(m.AlwaysLocalNets[iNdEx])))
			i--
			dAtA[i] = 0x2
			i--
			dAtA[i] = 0x8a
		}
	}
	if len(m.ReleasesURL) > 0 {
		i -= len(m.ReleasesURL)
		copy(dAtA[i:], m.ReleasesURL)
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(len(m.ReleasesURL)))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x82
	}
	{
		size, err := m.MinHomeDiskFree.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xfa
	if m.LimitBandwidthInLan {
		i--
		if m.LimitBandwidthInLan {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf0
	}
	if m.ProgressUpdateIntervalS != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.ProgressUpdateIntervalS))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe8
	}
	if m.CacheIgnoredFiles {
		i--
		if m.CacheIgnoredFiles {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe0
	}
	if m.KeepTemporariesH != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.KeepTemporariesH))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd8
	}
	if m.UpgradeToPreReleases {
		i--
		if m.UpgradeToPreReleases {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd0
	}
	if m.AutoUpgradeIntervalH != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.AutoUpgradeIntervalH))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc8
	}
	if m.URInitialDelayS != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.URInitialDelayS))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb8
	}
	if m.URPostInsecurely {
		i--
		if m.URPostInsecurely {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if len(m.URURL) > 0 {
		i -= len(m.URURL)
		copy(dAtA[i:], m.URURL)
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(len(m.URURL)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if len(m.URUniqueID) > 0 {
		i -= len(m.URUniqueID)
		copy(dAtA[i:], m.URUniqueID)
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(len(m.URUniqueID)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.URSeen != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.URSeen))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.URAccepted != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.URAccepted))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.NATTimeoutS != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.NATTimeoutS))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.NATRenewalM != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.NATRenewalM))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.NATLeaseM != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.NATLeaseM))
		i--
		dAtA[i] = 0x78
	}
	if m.NATEnabled {
		i--
		if m.NATEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if m.StartBrowser {
		i--
		if m.StartBrowser {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.RelayReconnectIntervalM != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.RelayReconnectIntervalM))
		i--
		dAtA[i] = 0x58
	}
	if m.RelaysEnabled {
		i--
		if m.RelaysEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.ReconnectIntervalS != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.ReconnectIntervalS))
		i--
		dAtA[i] = 0x48
	}
	if m.MaxRecvKbps != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.MaxRecvKbps))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxSendKbps != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.MaxSendKbps))
		i--
		dAtA[i] = 0x38
	}
	if len(m.LocalAnnMCAddr) > 0 {
		i -= len(m.LocalAnnMCAddr)
		copy(dAtA[i:], m.LocalAnnMCAddr)
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(len(m.LocalAnnMCAddr)))
		i--
		dAtA[i] = 0x32
	}
	if m.LocalAnnPort != 0 {
		i = encodeVarintOptionsconfiguration(dAtA, i, uint64(m.LocalAnnPort))
		i--
		dAtA[i] = 0x28
	}
	if m.LocalAnnEnabled {
		i--
		if m.LocalAnnEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.GlobalAnnEnabled {
		i--
		if m.GlobalAnnEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.RawGlobalAnnServers) > 0 {
		for iNdEx := len(m.RawGlobalAnnServers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RawGlobalAnnServers[iNdEx])
			copy(dAtA[i:], m.RawGlobalAnnServers[iNdEx])
			i = encodeVarintOptionsconfiguration(dAtA, i, uint64(len(m.RawGlobalAnnServers[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.RawListenAddresses) > 0 {
		for iNdEx := len(m.RawListenAddresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RawListenAddresses[iNdEx])
			copy(dAtA[i:], m.RawListenAddresses[iNdEx])
			i = encodeVarintOptionsconfiguration(dAtA, i, uint64(len(m.RawListenAddresses[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintOptionsconfiguration(dAtA []byte, offset int, v uint64) int {
	offset -= sovOptionsconfiguration(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OptionsConfiguration) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RawListenAddresses) > 0 {
		for _, s := range m.RawListenAddresses {
			l = len(s)
			n += 1 + l + sovOptionsconfiguration(uint64(l))
		}
	}
	if len(m.RawGlobalAnnServers) > 0 {
		for _, s := range m.RawGlobalAnnServers {
			l = len(s)
			n += 1 + l + sovOptionsconfiguration(uint64(l))
		}
	}
	if m.GlobalAnnEnabled {
		n += 2
	}
	if m.LocalAnnEnabled {
		n += 2
	}
	if m.LocalAnnPort != 0 {
		n += 1 + sovOptionsconfiguration(uint64(m.LocalAnnPort))
	}
	l = len(m.LocalAnnMCAddr)
	if l > 0 {
		n += 1 + l + sovOptionsconfiguration(uint64(l))
	}
	if m.MaxSendKbps != 0 {
		n += 1 + sovOptionsconfiguration(uint64(m.MaxSendKbps))
	}
	if m.MaxRecvKbps != 0 {
		n += 1 + sovOptionsconfiguration(uint64(m.MaxRecvKbps))
	}
	if m.ReconnectIntervalS != 0 {
		n += 1 + sovOptionsconfiguration(uint64(m.ReconnectIntervalS))
	}
	if m.RelaysEnabled {
		n += 2
	}
	if m.RelayReconnectIntervalM != 0 {
		n += 1 + sovOptionsconfiguration(uint64(m.RelayReconnectIntervalM))
	}
	if m.StartBrowser {
		n += 2
	}
	if m.NATEnabled {
		n += 2
	}
	if m.NATLeaseM != 0 {
		n += 1 + sovOptionsconfiguration(uint64(m.NATLeaseM))
	}
	if m.NATRenewalM != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.NATRenewalM))
	}
	if m.NATTimeoutS != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.NATTimeoutS))
	}
	if m.URAccepted != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.URAccepted))
	}
	if m.URSeen != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.URSeen))
	}
	l = len(m.URUniqueID)
	if l > 0 {
		n += 2 + l + sovOptionsconfiguration(uint64(l))
	}
	l = len(m.URURL)
	if l > 0 {
		n += 2 + l + sovOptionsconfiguration(uint64(l))
	}
	if m.URPostInsecurely {
		n += 3
	}
	if m.URInitialDelayS != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.URInitialDelayS))
	}
	if m.AutoUpgradeIntervalH != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.AutoUpgradeIntervalH))
	}
	if m.UpgradeToPreReleases {
		n += 3
	}
	if m.KeepTemporariesH != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.KeepTemporariesH))
	}
	if m.CacheIgnoredFiles {
		n += 3
	}
	if m.ProgressUpdateIntervalS != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.ProgressUpdateIntervalS))
	}
	if m.LimitBandwidthInLan {
		n += 3
	}
	l = m.MinHomeDiskFree.ProtoSize()
	n += 2 + l + sovOptionsconfiguration(uint64(l))
	l = len(m.ReleasesURL)
	if l > 0 {
		n += 2 + l + sovOptionsconfiguration(uint64(l))
	}
	if len(m.AlwaysLocalNets) > 0 {
		for _, s := range m.AlwaysLocalNets {
			l = len(s)
			n += 2 + l + sovOptionsconfiguration(uint64(l))
		}
	}
	if m.OverwriteRemoteDevNames {
		n += 3
	}
	if m.TempIndexMinBlocks != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.TempIndexMinBlocks))
	}
	if len(m.UnackedNotificationIDs) > 0 {
		for _, s := range m.UnackedNotificationIDs {
			l = len(s)
			n += 2 + l + sovOptionsconfiguration(uint64(l))
		}
	}
	if m.TrafficClass != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.TrafficClass))
	}
	l = len(m.DeprecatedDefaultFolderPath)
	if l > 0 {
		n += 2 + l + sovOptionsconfiguration(uint64(l))
	}
	if m.SetLowPriority {
		n += 3
	}
	if m.RawMaxFolderConcurrency != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.RawMaxFolderConcurrency))
	}
	l = len(m.CRURL)
	if l > 0 {
		n += 2 + l + sovOptionsconfiguration(uint64(l))
	}
	if m.CREnabled {
		n += 3
	}
	if m.StunKeepaliveStartS != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.StunKeepaliveStartS))
	}
	if m.StunKeepaliveMinS != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.StunKeepaliveMinS))
	}
	if len(m.RawStunServers) > 0 {
		for _, s := range m.RawStunServers {
			l = len(s)
			n += 2 + l + sovOptionsconfiguration(uint64(l))
		}
	}
	if m.DatabaseTuning != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.DatabaseTuning))
	}
	if m.RawMaxCIRequestKiB != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.RawMaxCIRequestKiB))
	}
	if m.AnnounceLANAddresses {
		n += 3
	}
	if m.SendFullIndexOnUpgrade {
		n += 3
	}
	if len(m.FeatureFlags) > 0 {
		for _, s := range m.FeatureFlags {
			l = len(s)
			n += 2 + l + sovOptionsconfiguration(uint64(l))
		}
	}
	if m.ConnectionLimitEnough != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.ConnectionLimitEnough))
	}
	if m.ConnectionLimitMax != 0 {
		n += 2 + sovOptionsconfiguration(uint64(m.ConnectionLimitMax))
	}
	if m.InsecureAllowOldTLSVersions {
		n += 3
	}
	if m.DeprecatedUPnPEnabled {
		n += 4
	}
	if m.DeprecatedUPnPLeaseM != 0 {
		n += 3 + sovOptionsconfiguration(uint64(m.DeprecatedUPnPLeaseM))
	}
	if m.DeprecatedUPnPRenewalM != 0 {
		n += 3 + sovOptionsconfiguration(uint64(m.DeprecatedUPnPRenewalM))
	}
	if m.DeprecatedUPnPTimeoutS != 0 {
		n += 3 + sovOptionsconfiguration(uint64(m.DeprecatedUPnPTimeoutS))
	}
	if len(m.DeprecatedRelayServers) > 0 {
		for _, s := range m.DeprecatedRelayServers {
			l = len(s)
			n += 3 + l + sovOptionsconfiguration(uint64(l))
		}
	}
	if m.DeprecatedMinHomeDiskFreePct != 0 {
		n += 11
	}
	if m.DeprecatedMaxConcurrentScans != 0 {
		n += 3 + sovOptionsconfiguration(uint64(m.DeprecatedMaxConcurrentScans))
	}
	return n
}

func sovOptionsconfiguration(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOptionsconfiguration(x uint64) (n int) {
	return sovOptionsconfiguration(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OptionsConfiguration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOptionsconfiguration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OptionsConfiguration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OptionsConfiguration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawListenAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawListenAddresses = append(m.RawListenAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawGlobalAnnServers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawGlobalAnnServers = append(m.RawGlobalAnnServers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalAnnEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.GlobalAnnEnabled = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocalAnnEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LocalAnnEnabled = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocalAnnPort", wireType)
			}
			m.LocalAnnPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LocalAnnPort |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocalAnnMCAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LocalAnnMCAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSendKbps", wireType)
			}
			m.MaxSendKbps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSendKbps |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRecvKbps", wireType)
			}
			m.MaxRecvKbps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRecvKbps |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReconnectIntervalS", wireType)
			}
			m.ReconnectIntervalS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReconnectIntervalS |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelaysEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RelaysEnabled = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayReconnectIntervalM", wireType)
			}
			m.RelayReconnectIntervalM = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RelayReconnectIntervalM |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBrowser", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.StartBrowser = bool(v != 0)
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NATEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NATEnabled = bool(v != 0)
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NATLeaseM", wireType)
			}
			m.NATLeaseM = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NATLeaseM |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NATRenewalM", wireType)
			}
			m.NATRenewalM = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NATRenewalM |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NATTimeoutS", wireType)
			}
			m.NATTimeoutS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NATTimeoutS |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field URAccepted", wireType)
			}
			m.URAccepted = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.URAccepted |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field URSeen", wireType)
			}
			m.URSeen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.URSeen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field URUniqueID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.URUniqueID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field URURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.URURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field URPostInsecurely", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.URPostInsecurely = bool(v != 0)
		case 23:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field URInitialDelayS", wireType)
			}
			m.URInitialDelayS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.URInitialDelayS |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 25:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoUpgradeIntervalH", wireType)
			}
			m.AutoUpgradeIntervalH = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AutoUpgradeIntervalH |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 26:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpgradeToPreReleases", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UpgradeToPreReleases = bool(v != 0)
		case 27:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeepTemporariesH", wireType)
			}
			m.KeepTemporariesH = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeepTemporariesH |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 28:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CacheIgnoredFiles", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CacheIgnoredFiles = bool(v != 0)
		case 29:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProgressUpdateIntervalS", wireType)
			}
			m.ProgressUpdateIntervalS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProgressUpdateIntervalS |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 30:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LimitBandwidthInLan", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LimitBandwidthInLan = bool(v != 0)
		case 31:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinHomeDiskFree", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinHomeDiskFree.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 32:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleasesURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReleasesURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 33:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlwaysLocalNets", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AlwaysLocalNets = append(m.AlwaysLocalNets, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 34:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OverwriteRemoteDevNames", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OverwriteRemoteDevNames = bool(v != 0)
		case 35:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TempIndexMinBlocks", wireType)
			}
			m.TempIndexMinBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TempIndexMinBlocks |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 36:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnackedNotificationIDs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnackedNotificationIDs = append(m.UnackedNotificationIDs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 37:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrafficClass", wireType)
			}
			m.TrafficClass = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrafficClass |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 38:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedDefaultFolderPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeprecatedDefaultFolderPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 39:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetLowPriority", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SetLowPriority = bool(v != 0)
		case 40:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawMaxFolderConcurrency", wireType)
			}
			m.RawMaxFolderConcurrency = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RawMaxFolderConcurrency |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 41:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CRURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CRURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 42:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CREnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CREnabled = bool(v != 0)
		case 43:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StunKeepaliveStartS", wireType)
			}
			m.StunKeepaliveStartS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StunKeepaliveStartS |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 44:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StunKeepaliveMinS", wireType)
			}
			m.StunKeepaliveMinS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StunKeepaliveMinS |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 45:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawStunServers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawStunServers = append(m.RawStunServers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 46:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatabaseTuning", wireType)
			}
			m.DatabaseTuning = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DatabaseTuning |= Tuning(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 47:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawMaxCIRequestKiB", wireType)
			}
			m.RawMaxCIRequestKiB = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RawMaxCIRequestKiB |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 48:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnnounceLANAddresses", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AnnounceLANAddresses = bool(v != 0)
		case 49:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendFullIndexOnUpgrade", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SendFullIndexOnUpgrade = bool(v != 0)
		case 50:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeatureFlags", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeatureFlags = append(m.FeatureFlags, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 51:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionLimitEnough", wireType)
			}
			m.ConnectionLimitEnough = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConnectionLimitEnough |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 52:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionLimitMax", wireType)
			}
			m.ConnectionLimitMax = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConnectionLimitMax |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 53:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InsecureAllowOldTLSVersions", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.InsecureAllowOldTLSVersions = bool(v != 0)
		case 9000:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedUPnPEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DeprecatedUPnPEnabled = bool(v != 0)
		case 9001:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedUPnPLeaseM", wireType)
			}
			m.DeprecatedUPnPLeaseM = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeprecatedUPnPLeaseM |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9002:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedUPnPRenewalM", wireType)
			}
			m.DeprecatedUPnPRenewalM = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeprecatedUPnPRenewalM |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9003:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedUPnPTimeoutS", wireType)
			}
			m.DeprecatedUPnPTimeoutS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeprecatedUPnPTimeoutS |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9004:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedRelayServers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeprecatedRelayServers = append(m.DeprecatedRelayServers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 9005:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedMinHomeDiskFreePct", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.DeprecatedMinHomeDiskFreePct = float64(math.Float64frombits(v))
		case 9006:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedMaxConcurrentScans", wireType)
			}
			m.DeprecatedMaxConcurrentScans = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeprecatedMaxConcurrentScans |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOptionsconfiguration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOptionsconfiguration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOptionsconfiguration(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOptionsconfiguration
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOptionsconfiguration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOptionsconfiguration
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOptionsconfiguration
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOptionsconfiguration
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOptionsconfiguration        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOptionsconfiguration          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOptionsconfiguration = fmt.Errorf("proto: unexpected end of group")
)
